//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Yar.RESYAR
{

    public partial class INCUSTOMER : XPLiteObject
    {
        string fNAME;
        [Size(50)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>(nameof(NAME), ref fNAME, value); }
        }
        string fCUSTOMERALIAS;
        [Key]
        [Size(20)]
        public string CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<string>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        string fNUMS;
        [Size(5)]
        public string NUMS
        {
            get { return fNUMS; }
            set { SetPropertyValue<string>(nameof(NUMS), ref fNUMS, value); }
        }
    }

}
