//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Yar.RESYAR
{

    public partial class ROWREGDOC : XPLiteObject
    {
        double fPRICE;
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        double fSUMALL;
        public double SUMALL
        {
            get { return fSUMALL; }
            set { SetPropertyValue<double>(nameof(SUMALL), ref fSUMALL, value); }
        }
        string fFORMULA;
        [Size(30)]
        public string FORMULA
        {
            get { return fFORMULA; }
            set { SetPropertyValue<string>(nameof(FORMULA), ref fFORMULA, value); }
        }
        string fCUSTID;
        [Indexed(@"ROWCUSTNUM", Name = @"ROWREGDOC_CUSTID_ROWCUSTNUM")]
        [Size(14)]
        public string CUSTID
        {
            get { return fCUSTID; }
            set { SetPropertyValue<string>(nameof(CUSTID), ref fCUSTID, value); }
        }
        double fDCOUNT;
        public double DCOUNT
        {
            get { return fDCOUNT; }
            set { SetPropertyValue<double>(nameof(DCOUNT), ref fDCOUNT, value); }
        }
        int fCOUN;
        public int COUN
        {
            get { return fCOUN; }
            set { SetPropertyValue<int>(nameof(COUN), ref fCOUN, value); }
        }
        int fROWCUSTNUM;
        public int ROWCUSTNUM
        {
            get { return fROWCUSTNUM; }
            set { SetPropertyValue<int>(nameof(ROWCUSTNUM), ref fROWCUSTNUM, value); }
        }
        string fKOMENT;
        [Size(50)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        short fH;
        public short H
        {
            get { return fH; }
            set { SetPropertyValue<short>(nameof(H), ref fH, value); }
        }
        short fW;
        public short W
        {
            get { return fW; }
            set { SetPropertyValue<short>(nameof(W), ref fW, value); }
        }
        string fALIASNOM;
        [Size(80)]
        public string ALIASNOM
        {
            get { return fALIASNOM; }
            set { SetPropertyValue<string>(nameof(ALIASNOM), ref fALIASNOM, value); }
        }
        string fALIASGR;
        [Size(5)]
        public string ALIASGR
        {
            get { return fALIASGR; }
            set { SetPropertyValue<string>(nameof(ALIASGR), ref fALIASGR, value); }
        }
        string fONEALIAS;
        [Size(5)]
        public string ONEALIAS
        {
            get { return fONEALIAS; }
            set { SetPropertyValue<string>(nameof(ONEALIAS), ref fONEALIAS, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(14)]
            [Persistent("REGDOCID")]
            public string REGDOCID { get; set; }
            [Persistent("ROWNUM")]
            public int ROWNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
