//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Yar.RESYAR
{

    public partial class TENDERS : XPLiteObject
    {
        DateTime fDATECREATE;
        public DateTime DATECREATE
        {
            get { return fDATECREATE; }
            set { SetPropertyValue<DateTime>(nameof(DATECREATE), ref fDATECREATE, value); }
        }
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fTENNAME;
        [Size(50)]
        public string TENNAME
        {
            get { return fTENNAME; }
            set { SetPropertyValue<string>(nameof(TENNAME), ref fTENNAME, value); }
        }
        short fDEL;
        [ColumnDbDefaultValue("0")]
        public short DEL
        {
            get { return fDEL; }
            set { SetPropertyValue<short>(nameof(DEL), ref fDEL, value); }
        }
        short fISCLOSE;
        [ColumnDbDefaultValue("0")]
        public short ISCLOSE
        {
            get { return fISCLOSE; }
            set { SetPropertyValue<short>(nameof(ISCLOSE), ref fISCLOSE, value); }
        }
        string fUSERNAME;
        [Size(31)]
        public string USERNAME
        {
            get { return fUSERNAME; }
            set { SetPropertyValue<string>(nameof(USERNAME), ref fUSERNAME, value); }
        }
    }

}
