//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Yar.RESYAR
{

    public partial class WORKOTD : XPLiteObject
    {
        int fCOUN_;
        public int COUN_
        {
            get { return fCOUN_; }
            set { SetPropertyValue<int>(nameof(COUN_), ref fCOUN_, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(14)]
            [Persistent("CUSTID")]
            public string CUSTID { get; set; }
            [Size(14)]
            [Persistent("KODOTD")]
            public string KODOTD { get; set; }
            [Persistent("ROWNUM")]
            public int ROWNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
