//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressElement()
        {
            this.AddressItems = new HashSet<AddressItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AddressElementType_Id { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string Code { get; set; }
    
        public virtual AddressElementType AddressElementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressItem> AddressItems { get; set; }
    }
}
