//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractAddresses = new HashSet<ContractAddress>();
            this.ContractPrices = new HashSet<ContractPrice>();
            this.ContractShippingSquares = new HashSet<ContractShippingSquare>();
            this.ContractTenderFormulas = new HashSet<ContractTenderFormula>();
            this.PriceSquareCustoms = new HashSet<PriceSquareCustom>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<long> Num { get; set; }
        public Nullable<System.Guid> ContractType_Id { get; set; }
        public Nullable<System.Guid> Division_Id { get; set; }
        public Nullable<System.Guid> Customer_Id { get; set; }
        public Nullable<System.Guid> Coworker_Id { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<System.Guid> PaymentType_Id { get; set; }
        public Nullable<short> PaymentBeforeDay { get; set; }
        public Nullable<double> PaymentBeforePercent { get; set; }
        public Nullable<int> PaymentBeforeAmount { get; set; }
        public Nullable<double> PaymentReadyPercent { get; set; }
        public Nullable<int> PaymentReadyAmount { get; set; }
        public Nullable<short> PaymentAfterDay { get; set; }
        public Nullable<int> PaymentCreditLimit { get; set; }
        public Nullable<short> BillValidityPeriod { get; set; }
        public Nullable<System.Guid> PriceRegion_Id { get; set; }
        public Nullable<short> PriceChangeDayInfo { get; set; }
        public Nullable<System.DateTime> PriceChangeDate { get; set; }
        public string EditorPrice { get; set; }
        public string EditorShippingPrice { get; set; }
        public Nullable<System.DateTime> ShippingPriceChangeDate { get; set; }
        public Nullable<bool> Spec { get; set; }
        public Nullable<byte> DaysForProduct { get; set; }
        public Nullable<System.TimeSpan> DateTransferTime { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAddress> ContractAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractPrice> ContractPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractShippingSquare> ContractShippingSquares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTenderFormula> ContractTenderFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceSquareCustom> PriceSquareCustoms { get; set; }
        public virtual Coworker Coworker { get; set; }
        public virtual Division Division { get; set; }
    }
}
