//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTenderFormula
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Contract_Id { get; set; }
        public Nullable<System.Guid> Formula_Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> SquReady { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
