//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAddress
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Contract_Id { get; set; }
        public Nullable<System.Guid> Address_Id { get; set; }
        public string District { get; set; }
        public string DistanceMark { get; set; }
        public Nullable<int> DistanceLength { get; set; }
        public string Comment { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
