//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoworkerContact
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Coworker_Id { get; set; }
        public Nullable<System.Guid> ContactType_Id { get; set; }
        public string Value { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Coworker Coworker { get; set; }
    }
}
