//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoworkerPosition
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Division_Id { get; set; }
        public Nullable<System.Guid> WorkPosition_Id { get; set; }
        public Nullable<System.Guid> Coworker_Id { get; set; }
        public Nullable<bool> Default { get; set; }
    
        public virtual WorkPosition WorkPosition { get; set; }
        public virtual Coworker Coworker { get; set; }
        public virtual Division Division { get; set; }
    }
}
