//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProp
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Customer_Id { get; set; }
        public Nullable<System.Guid> CustomerPropType_Id { get; set; }
        public byte[] Value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerPropType CustomerPropType { get; set; }
    }
}
