//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
            this.Contracts = new HashSet<Contract>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.DivisionCustomers = new HashSet<DivisionCustomer>();
            this.DivisionSignatures = new HashSet<DivisionSignature>();
            this.Orders = new HashSet<Order>();
            this.CustomerProps = new HashSet<CustomerProp>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustomerType_Id { get; set; }
        public Nullable<System.Guid> OPF_Id { get; set; }
        public string NameAlias { get; set; }
        public string NameFull { get; set; }
        public string NameShort { get; set; }
        public string NameForeign { get; set; }
        public string NameFirst { get; set; }
        public string NameMiddle { get; set; }
        public string NameLast { get; set; }
        public Nullable<System.Guid> Currency_Id { get; set; }
        public Nullable<System.Guid> Country_Id { get; set; }
        public string Inn { get; set; }
        public string Kpp { get; set; }
        public string Ogrn { get; set; }
        public string Okpo { get; set; }
        public string TaxNumberForeign { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<System.Guid> Manager_Id { get; set; }
        public Nullable<System.Guid> TypeBarcode_Id { get; set; }
        public string Code_1C { get; set; }
        public Nullable<bool> OrderLock { get; set; }
        public Nullable<bool> ProdLoсk { get; set; }
        public Nullable<bool> TaxUsn { get; set; }
        public Nullable<bool> TaxEnvd { get; set; }
        public Nullable<bool> IsOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionCustomer> DivisionCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionSignature> DivisionSignatures { get; set; }
        public virtual OPF OPF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProp> CustomerProps { get; set; }
    }
}
