//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionSignature
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Division_Id { get; set; }
        public Nullable<System.Guid> DocumentType_Id { get; set; }
        public Nullable<System.Guid> DocumentSignatureType_Id { get; set; }
        public Nullable<System.Guid> Coworker_Id { get; set; }
        public string DocCoworkerPosition { get; set; }
        public string DocBasics { get; set; }
        public Nullable<System.Guid> Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DocumentSignatureType DocumentSignatureType { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Coworker Coworker { get; set; }
        public virtual Division Division { get; set; }
    }
}
