//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionContact
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Division_Id { get; set; }
        public Nullable<System.Guid> DepartmentType_Id { get; set; }
        public Nullable<System.Guid> ContactType_Id { get; set; }
        public string Value { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual DepartmentType DepartmentType { get; set; }
        public virtual Division Division { get; set; }
    }
}
