//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSignature
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DocumentType_Id { get; set; }
        public Nullable<System.Guid> DocumentSignatureType_Id { get; set; }
    
        public virtual DocumentSignatureType DocumentSignatureType { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
