//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormulaItem()
        {
            this.FormulaItems = new HashSet<FormulaItem>();
            this.FormulaItemFrameProperties = new HashSet<FormulaItemFrameProperty>();
            this.FormulaItemGlassProperties = new HashSet<FormulaItemGlassProperty>();
            this.FormulaItemTriplexProperties = new HashSet<FormulaItemTriplexProperty>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Formula_Id { get; set; }
        public Nullable<System.Guid> MaterialNom_Id { get; set; }
        public Nullable<short> Position { get; set; }
        public Nullable<System.Guid> ParentItem_Id { get; set; }
        public string ItemStr { get; set; }
        public Nullable<System.Guid> Material_Id { get; set; }
    
        public virtual Formula Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItem> FormulaItems { get; set; }
        public virtual FormulaItem ParentItem { get; set; }
        public virtual Material Material { get; set; }
        public virtual MaterialNom MaterialNom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItemFrameProperty> FormulaItemFrameProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItemGlassProperty> FormulaItemGlassProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItemTriplexProperty> FormulaItemTriplexProperties { get; set; }
    }
}
