//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaItemFrameProperty
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FormulaItem_Id { get; set; }
        public Nullable<double> GermDepth { get; set; }
        public Nullable<bool> Tolling { get; set; }
        public Nullable<bool> Gaz { get; set; }
    
        public virtual FormulaItem FormulaItem { get; set; }
    }
}
