//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialNom()
        {
            this.FormulaItems = new HashSet<FormulaItem>();
            this.MaterialSizeTypes = new HashSet<MaterialSizeType>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> VendorMaterialNom_Id { get; set; }
        public Nullable<System.Guid> MaterialSizeType_Id { get; set; }
        public string Code1C { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItem> FormulaItems { get; set; }
        public virtual MaterialSizeType MaterialSizeType { get; set; }
        public virtual VendorMaterialNom VendorMaterialNom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSizeType> MaterialSizeTypes { get; set; }
    }
}
