//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderRow()
        {
            this.OrderRowSlozs = new HashSet<OrderRowSloz>();
        }
    
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
        public Nullable<int> OverallW { get; set; }
        public Nullable<int> OverallH { get; set; }
        public string FormulaStr { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Mark { get; set; }
        public string Barcode { get; set; }
        public string Comment { get; set; }
        public Nullable<double> PriceSqu { get; set; }
        public Nullable<double> PriceRatio { get; set; }
        public Nullable<double> PriceItem { get; set; }
        public Nullable<double> PriceRow { get; set; }
        public Nullable<System.Guid> Formula_Id { get; set; }
        public Nullable<System.Guid> Shape_Id { get; set; }
    
        public virtual Formula Formula { get; set; }
        public virtual Order Order { get; set; }
        public virtual Shape Shape { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRowSloz> OrderRowSlozs { get; set; }
    }
}
