//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderRows = new HashSet<OrderRow>();
            this.OrderStatusHistories = new HashSet<OrderStatusHistory>();
        }
    
        public System.Guid Id { get; set; }
        public long Num { get; set; }
        public Nullable<System.Guid> Division_Id { get; set; }
        public System.DateTime DateInput { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public Nullable<System.Guid> Customer_Id { get; set; }
        public string NumCustomer { get; set; }
        public Nullable<System.DateTime> DateCustomer { get; set; }
        public Nullable<System.Guid> PartyId { get; set; }
        public Nullable<System.Guid> Dogovor_Id { get; set; }
        public Nullable<System.Guid> Account_Id { get; set; }
        public Nullable<System.Guid> Address_Id { get; set; }
        public Nullable<bool> SelfShipping { get; set; }
        public string Comment { get; set; }
        public Nullable<double> PriceAmount { get; set; }
        public Nullable<double> PriceRun { get; set; }
        public Nullable<System.Guid> PaymentType_Id { get; set; }
        public Nullable<System.Guid> OrderStatus_Id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRow> OrderRows { get; set; }
        public virtual Division Division { get; set; }
        public virtual OrderStatus OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; }
    }
}
