//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusHistory
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public Nullable<System.Guid> NewOrderStatus_Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual User User { get; set; }
    }
}
