//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceSprosComponent
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SprosComponent_Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.Guid> Price_Id { get; set; }
    
        public virtual Price Price1 { get; set; }
    }
}
