//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceSloz
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SlozType_Id { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Delta { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public string Editor { get; set; }
        public Nullable<System.Guid> Price_Id { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual SlozType SlozType { get; set; }
    }
}
