//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTreeItem
    {
        public System.Guid Id { get; set; }
        public System.Guid Role_Id { get; set; }
        public System.Guid TreeItem_Id { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Write { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual TreeItem TreeItem { get; set; }
    }
}
