//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShapePoint
    {
        public System.Guid Id { get; set; }
        public string PointName { get; set; }
        public Nullable<double> Point_X { get; set; }
        public Nullable<double> Point_Y { get; set; }
        public Nullable<double> PointRadius { get; set; }
        public System.Guid Shape_Id { get; set; }
    
        public virtual Shape Shape { get; set; }
    }
}
