//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shape
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shape()
        {
            this.OrderRows = new HashSet<OrderRow>();
            this.ShapePoints = new HashSet<ShapePoint>();
        }
    
        public System.Guid Id { get; set; }
        public int SidesCount { get; set; }
        public string CatalogNumber { get; set; }
        public bool IsCatalog { get; set; }
        public Nullable<bool> IsCuttingGlass { get; set; }
        public Nullable<bool> IsBendingDistanceFrame { get; set; }
        public Nullable<bool> IsFormSealing { get; set; }
        public Nullable<bool> IsGasFillingForm { get; set; }
        public Nullable<bool> IsVertBendingMashineRobot { get; set; }
        public Nullable<bool> IsVertMashineEdgeMaking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRow> OrderRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShapePoint> ShapePoints { get; set; }
    }
}
