//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocratEntities : DbContext
    {
        public SocratEntities()
            : base("SocratDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressContact> AddressContacts { get; set; }
        public virtual DbSet<AddressElement> AddressElements { get; set; }
        public virtual DbSet<AddressElementType> AddressElementTypes { get; set; }
        public virtual DbSet<AddressItem> AddressItems { get; set; }
        public virtual DbSet<AppParam> AppParams { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractAddress> ContractAddresses { get; set; }
        public virtual DbSet<ContractPrice> ContractPrices { get; set; }
        public virtual DbSet<ContractShippingSquare> ContractShippingSquares { get; set; }
        public virtual DbSet<ContractTenderFormula> ContractTenderFormulas { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CoworkerContact> CoworkerContacts { get; set; }
        public virtual DbSet<CoworkerPosition> CoworkerPositions { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerPropType> CustomerPropTypes { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<DateTimeRange> DateTimeRanges { get; set; }
        public virtual DbSet<DepartmentType> DepartmentTypes { get; set; }
        public virtual DbSet<DivisionContact> DivisionContacts { get; set; }
        public virtual DbSet<DivisionCustomer> DivisionCustomers { get; set; }
        public virtual DbSet<DivisionSignature> DivisionSignatures { get; set; }
        public virtual DbSet<DocumentSignature> DocumentSignatures { get; set; }
        public virtual DbSet<DocumentSignatureType> DocumentSignatureTypes { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<FormulaItem> FormulaItems { get; set; }
        public virtual DbSet<FormulaItemFrameProperty> FormulaItemFrameProperties { get; set; }
        public virtual DbSet<FormulaItemGlassProperty> FormulaItemGlassProperties { get; set; }
        public virtual DbSet<FormulaItemTriplexProperty> FormulaItemTriplexProperties { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialMarkType> MaterialMarkTypes { get; set; }
        public virtual DbSet<MaterialNom> MaterialNoms { get; set; }
        public virtual DbSet<MaterialSizeType> MaterialSizeTypes { get; set; }
        public virtual DbSet<MaterialSpecProperty> MaterialSpecProperties { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<Measure> Measures { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<OPF> OPFs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderRow> OrderRows { get; set; }
        public virtual DbSet<OrderRowSloz> OrderRowSlozs { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<PriceFarmeType> PriceFarmeTypes { get; set; }
        public virtual DbSet<PriceFilm> PriceFilms { get; set; }
        public virtual DbSet<PriceGlassCut> PriceGlassCuts { get; set; }
        public virtual DbSet<PriceMargin> PriceMargins { get; set; }
        public virtual DbSet<PriceSloz> PriceSlozs { get; set; }
        public virtual DbSet<PriceSpro> PriceSpros { get; set; }
        public virtual DbSet<PriceSprosComponent> PriceSprosComponents { get; set; }
        public virtual DbSet<PriceSquare> PriceSquares { get; set; }
        public virtual DbSet<PriceSquareCustom> PriceSquareCustoms { get; set; }
        public virtual DbSet<PriceType> PriceTypes { get; set; }
        public virtual DbSet<Processing> Processings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleTreeItem> RoleTreeItems { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<ShapePoint> ShapePoints { get; set; }
        public virtual DbSet<SlozType> SlozTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TradeMark> TradeMarks { get; set; }
        public virtual DbSet<TreeItemType> TreeItemTypes { get; set; }
        public virtual DbSet<VendorMaterial> VendorMaterials { get; set; }
        public virtual DbSet<VendorMaterialNom> VendorMaterialNoms { get; set; }
        public virtual DbSet<WorkPosition> WorkPositions { get; set; }
        public virtual DbSet<TreeItem> TreeItems { get; set; }
        public virtual DbSet<CustomerProp> CustomerProps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Coworker> Coworkers { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<OrderStatusHistory> OrderStatusHistories { get; set; }
    }
}
