//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TradeMark()
        {
            this.VendorMaterialNoms = new HashSet<VendorMaterialNom>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Material_Id { get; set; }
        public Nullable<System.Guid> Brand_Id { get; set; }
        public string Name { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMaterialNom> VendorMaterialNoms { get; set; }
    }
}
