//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreeItem()
        {
            this.RoleTreeItems = new HashSet<RoleTreeItem>();
            this.TreeItems = new HashSet<TreeItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TreeItemType_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentTreeItem_Id { get; set; }
        public Nullable<System.Guid> Module_Id { get; set; }
        public Nullable<short> SortNum { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleTreeItem> RoleTreeItems { get; set; }
        public virtual TreeItemType TreeItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreeItem> TreeItems { get; set; }
        public virtual TreeItem ParentTreeItem { get; set; }
    }
}
