//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaterial
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Vendor_Id { get; set; }
        public Nullable<System.Guid> Material_Id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
