//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaterialNom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorMaterialNom()
        {
            this.MaterialNoms = new HashSet<MaterialNom>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Vendor_Id { get; set; }
        public Nullable<System.Guid> Material_Id { get; set; }
        public Nullable<System.Guid> Brand_Id { get; set; }
        public Nullable<System.Guid> TradeMark_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> MaterialMarkType_Id { get; set; }
        public string ColorRAL { get; set; }
        public Nullable<double> ColorTransparency { get; set; }
        public string Mark { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Material Material { get; set; }
        public virtual MaterialMarkType MaterialMarkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialNom> MaterialNoms { get; set; }
        public virtual TradeMark TradeMark { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
