//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public Nullable<long> LogType { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
        public string UserLogin { get; set; }
        public string Header { get; set; }
        public string MachineName { get; set; }
        public string AppName { get; set; }
        public string ExMessage { get; set; }
        public string ExSource { get; set; }
        public string ExStackTrace { get; set; }
        public string HelpLink { get; set; }
        public string Version { get; set; }
    }
}
