//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socrat.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceSquareCustom
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Contract_Id { get; set; }
        public Nullable<System.Guid> PriceSquare_Id { get; set; }
        public Nullable<double> Squ { get; set; }
        public Nullable<double> SquRatio { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual PriceSquare PriceSquare { get; set; }
    }
}
