//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class BRAK_LIST : XPLiteObject
    {
        string fCUSTID;
        [Size(14)]
        public string CUSTID
        {
            get { return fCUSTID; }
            set { SetPropertyValue<string>(nameof(CUSTID), ref fCUSTID, value); }
        }
        DateTime fBRAK_DATE;
        public DateTime BRAK_DATE
        {
            get { return fBRAK_DATE; }
            set { SetPropertyValue<DateTime>(nameof(BRAK_DATE), ref fBRAK_DATE, value); }
        }
        string fOPERATOR;
        [Size(30)]
        public string OPERATOR
        {
            get { return fOPERATOR; }
            set { SetPropertyValue<string>(nameof(OPERATOR), ref fOPERATOR, value); }
        }
        DateTime fEDIT;
        public DateTime EDIT
        {
            get { return fEDIT; }
            set { SetPropertyValue<DateTime>(nameof(EDIT), ref fEDIT, value); }
        }
        int fBRAKID;
        [Key]
        public int BRAKID
        {
            get { return fBRAKID; }
            set { SetPropertyValue<int>(nameof(BRAKID), ref fBRAKID, value); }
        }
        int fROWNUM;
        public int ROWNUM
        {
            get { return fROWNUM; }
            set { SetPropertyValue<int>(nameof(ROWNUM), ref fROWNUM, value); }
        }
        int fGLASSPOS;
        public int GLASSPOS
        {
            get { return fGLASSPOS; }
            set { SetPropertyValue<int>(nameof(GLASSPOS), ref fGLASSPOS, value); }
        }
        int fPOSCOUNT;
        public int POSCOUNT
        {
            get { return fPOSCOUNT; }
            set { SetPropertyValue<int>(nameof(POSCOUNT), ref fPOSCOUNT, value); }
        }
        int fGLASSCOUNT;
        public int GLASSCOUNT
        {
            get { return fGLASSCOUNT; }
            set { SetPropertyValue<int>(nameof(GLASSCOUNT), ref fGLASSCOUNT, value); }
        }
        BRAKBORN fBB_ID;
        [Association(@"BRAK_LISTReferencesBRAKBORN")]
        public BRAKBORN BB_ID
        {
            get { return fBB_ID; }
            set { SetPropertyValue<BRAKBORN>(nameof(BB_ID), ref fBB_ID, value); }
        }
        BRAKLOCATION fBL_ID;
        [Association(@"BRAK_LISTReferencesBRAKLOCATION")]
        public BRAKLOCATION BL_ID
        {
            get { return fBL_ID; }
            set { SetPropertyValue<BRAKLOCATION>(nameof(BL_ID), ref fBL_ID, value); }
        }
        BRAKOSN fBO_ID;
        [Association(@"BRAK_LISTReferencesBRAKOSN")]
        public BRAKOSN BO_ID
        {
            get { return fBO_ID; }
            set { SetPropertyValue<BRAKOSN>(nameof(BO_ID), ref fBO_ID, value); }
        }
        string fBRAK_KOMENT;
        [Size(50)]
        public string BRAK_KOMENT
        {
            get { return fBRAK_KOMENT; }
            set { SetPropertyValue<string>(nameof(BRAK_KOMENT), ref fBRAK_KOMENT, value); }
        }
        string fMANAGER;
        [Size(31)]
        public string MANAGER
        {
            get { return fMANAGER; }
            set { SetPropertyValue<string>(nameof(MANAGER), ref fMANAGER, value); }
        }
    }

}
