//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class BRAKBORN : XPLiteObject
    {
        int fBB_ID;
        [Key]
        public int BB_ID
        {
            get { return fBB_ID; }
            set { SetPropertyValue<int>(nameof(BB_ID), ref fBB_ID, value); }
        }
        string fBB_NAME;
        [Size(50)]
        public string BB_NAME
        {
            get { return fBB_NAME; }
            set { SetPropertyValue<string>(nameof(BB_NAME), ref fBB_NAME, value); }
        }
        string fBB_1C;
        [Size(3)]
        public string BB_1C
        {
            get { return fBB_1C; }
            set { SetPropertyValue<string>(nameof(BB_1C), ref fBB_1C, value); }
        }
        [Association(@"BRAK_LISTReferencesBRAKBORN")]
        public XPCollection<BRAK_LIST> BRAK_LISTs { get { return GetCollection<BRAK_LIST>(nameof(BRAK_LISTs)); } }
    }

}
