//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class COLORZAL : XPLiteObject
    {
        string fCOLOR;
        [Key]
        [Size(20)]
        public string COLOR
        {
            get { return fCOLOR; }
            set { SetPropertyValue<string>(nameof(COLOR), ref fCOLOR, value); }
        }
        string fKOMENT;
        [Size(20)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
    }

}
