//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(AVTO),
            typeof(BARCODE),
            typeof(BRAK_LIST),
            typeof(BRAKBORN),
            typeof(BRAKLOCATION),
            typeof(BRAKOSN),
            typeof(COLORZAL),
            typeof(CUST),
            typeof(CUSTOMER),
            typeof(CUSTOMER_ADDRESS),
            typeof(CUSTOMER_CONTACTS),
            typeof(CUSTOMER_EVENTS_PERIODS),
            typeof(CUSTOMER_MANAGER),
            typeof(CUSTOMER_MESSAGE_EVENTS),
            typeof(CUSTOMER_PRICE),
            typeof(CUSTSTATUS),
            typeof(DOGOVOR),
            typeof(FIGURE),
            typeof(FIGURECOORD),
            typeof(FILMS),
            typeof(FILMTYPE),
            typeof(FORM),
            typeof(FORMCATALOG),
            typeof(FORMCHECK),
            typeof(FORMMEMBERSHIP),
            typeof(FORMPARAM),
            typeof(FRAME_TYPE),
            typeof(GLASS),
            typeof(GLASS_STRUCTURE),
            typeof(GLASSHPROC),
            typeof(GLASSNOM),
            typeof(GLASSPROCESSING),
            typeof(GLASSPROCESSINGTYPE),
            typeof(GLASSTYPE),
            typeof(GRNOM),
            typeof(INCUSTOMER),
            typeof(KURS),
            typeof(LIMIT),
            typeof(LINE),
            typeof(LONGTEXTZURNAL),
            typeof(MESSAGE_EVENT_TYPES),
            typeof(MESSAGES),
            typeof(NOMS),
            typeof(NORMSPIS),
            typeof(ONE),
            typeof(OPZS_REEXPORT),
            typeof(ORDER),
            typeof(ORDER_ROW),
            typeof(ORDER_ROWDETAIL),
            typeof(ORDER_SATUS),
            typeof(OTDEL),
            typeof(OUTCROPSIZE),
            typeof(OUTCROPTYPE),
            typeof(PACKETS),
            typeof(PARSER),
            typeof(PARSER_CALCTYPE),
            typeof(PARSER_FIELDS_HEAD),
            typeof(PARSER_FIELDS_TABLE),
            typeof(PARSER_HEAD),
            typeof(PARSER_HEAD_ADR),
            typeof(PARSER_TABLE),
            typeof(PARSER_TABLE_ADR),
            typeof(PASP),
            typeof(PFCUST),
            typeof(PLATFORM),
            typeof(POOLS),
            typeof(PP_GRANT),
            typeof(PP_ROLE),
            typeof(PP_ROLE_GRANTS),
            typeof(PP_USER_GRANTS),
            typeof(PP_USER_ROLE),
            typeof(PPCUST),
            typeof(PRICE_BASE),
            typeof(PRICE_BFORMULA),
            typeof(PRICE_CUTGLASS),
            typeof(PRICE_FILM),
            typeof(PRICE_FRAME),
            typeof(PRICE_FRAME_TYPE),
            typeof(PRICE_MARGINS),
            typeof(PRICE_RECALCTYPE),
            typeof(PRICE_SLOZ),
            typeof(PRICE_SPROS),
            typeof(PRICE_SPROSCOMPONENT),
            typeof(PRICE_SQUARE),
            typeof(PRICEFILM),
            typeof(PRICEGLASS),
            typeof(PRICES),
            typeof(PRICESPROS),
            typeof(PRICESTYPE),
            typeof(PRICEZAL),
            typeof(REF_XONE),
            typeof(REGDOC),
            typeof(ROUTETYPE),
            typeof(ROWCUST),
            typeof(ROWCUST_OPTID),
            typeof(ROWCUST_RESTORATION),
            typeof(ROWCUST_SLOZ),
            typeof(ROWCUSTFORMPARAM),
            typeof(ROWCUSTPROCESS),
            typeof(ROWCUSTPROCESSPARAM),
            typeof(ROWREGDOC),
            typeof(ROWTENDER),
            typeof(SLOZ_TYPE),
            typeof(SORTPIR),
            typeof(SPROS),
            typeof(SPROSCC),
            typeof(SPROSCOMPONENT),
            typeof(SPROSCOMPONENTTYPE),
            typeof(TEAM),
            typeof(TEMP_FORMUL),
            typeof(TENDERCUST),
            typeof(TENDERFORMULA),
            typeof(TENDEROWNER),
            typeof(TENDERS),
            typeof(TRIPLEX),
            typeof(TRIPLEX_FILMLAYER),
            typeof(TRIPLEX_GLASSLAYER),
            typeof(TYPE3GLASS),
            typeof(TYPEBRAK),
            typeof(TYPEDOC),
            typeof(TYPEFORMULA),
            typeof(TYPEGLASS),
            typeof(TYPEOSN),
            typeof(TYPERAMKA),
            typeof(TYPES),
            typeof(TYPESPROS),
            typeof(TYPETEAM),
            typeof(VARCONST),
            typeof(WORKOTD),
            typeof(WORKPROCESS),
            typeof(WORKTEAM),
            typeof(ZAKSTAMP)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["RESMIN"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
