//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER : XPLiteObject
    {
        string fKONTAKT;
        [Size(30)]
        public string KONTAKT
        {
            get { return fKONTAKT; }
            set { SetPropertyValue<string>(nameof(KONTAKT), ref fKONTAKT, value); }
        }
        string fEMAIL;
        [Size(30)]
        public string EMAIL
        {
            get { return fEMAIL; }
            set { SetPropertyValue<string>(nameof(EMAIL), ref fEMAIL, value); }
        }
        string fRS;
        [Size(30)]
        public string RS
        {
            get { return fRS; }
            set { SetPropertyValue<string>(nameof(RS), ref fRS, value); }
        }
        string fKS;
        [Size(30)]
        public string KS
        {
            get { return fKS; }
            set { SetPropertyValue<string>(nameof(KS), ref fKS, value); }
        }
        double fLG2KFP;
        public double LG2KFP
        {
            get { return fLG2KFP; }
            set { SetPropertyValue<double>(nameof(LG2KFP), ref fLG2KFP, value); }
        }
        double fLG3KFP;
        public double LG3KFP
        {
            get { return fLG3KFP; }
            set { SetPropertyValue<double>(nameof(LG3KFP), ref fLG3KFP, value); }
        }
        double fFIXPRICE;
        public double FIXPRICE
        {
            get { return fFIXPRICE; }
            set { SetPropertyValue<double>(nameof(FIXPRICE), ref fFIXPRICE, value); }
        }
        double fKURS;
        public double KURS
        {
            get { return fKURS; }
            set { SetPropertyValue<double>(nameof(KURS), ref fKURS, value); }
        }
        string fNAME;
        [Size(50)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>(nameof(NAME), ref fNAME, value); }
        }
        string fBANK;
        [Size(50)]
        public string BANK
        {
            get { return fBANK; }
            set { SetPropertyValue<string>(nameof(BANK), ref fBANK, value); }
        }
        int fLG2KPR;
        public int LG2KPR
        {
            get { return fLG2KPR; }
            set { SetPropertyValue<int>(nameof(LG2KPR), ref fLG2KPR, value); }
        }
        int fLG3KPR;
        public int LG3KPR
        {
            get { return fLG3KPR; }
            set { SetPropertyValue<int>(nameof(LG3KPR), ref fLG3KPR, value); }
        }
        int fLG2KAN;
        public int LG2KAN
        {
            get { return fLG2KAN; }
            set { SetPropertyValue<int>(nameof(LG2KAN), ref fLG2KAN, value); }
        }
        int fLG3KAN;
        public int LG3KAN
        {
            get { return fLG3KAN; }
            set { SetPropertyValue<int>(nameof(LG3KAN), ref fLG3KAN, value); }
        }
        string fADRESGRUZ;
        [Size(250)]
        public string ADRESGRUZ
        {
            get { return fADRESGRUZ; }
            set { SetPropertyValue<string>(nameof(ADRESGRUZ), ref fADRESGRUZ, value); }
        }
        CUSTOMER_MANAGER fMANAGERID;
        [Association(@"CUSTOMERReferencesCUSTOMER_MANAGER")]
        public CUSTOMER_MANAGER MANAGERID
        {
            get { return fMANAGERID; }
            set { SetPropertyValue<CUSTOMER_MANAGER>(nameof(MANAGERID), ref fMANAGERID, value); }
        }
        int fDOGOVORDEF;
        public int DOGOVORDEF
        {
            get { return fDOGOVORDEF; }
            set { SetPropertyValue<int>(nameof(DOGOVORDEF), ref fDOGOVORDEF, value); }
        }
        string fCUSTOMERALIAS;
        [Key]
        [Size(20)]
        public string CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<string>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        string fADDRES;
        public string ADDRES
        {
            get { return fADDRES; }
            set { SetPropertyValue<string>(nameof(ADDRES), ref fADDRES, value); }
        }
        string fTYPEBARCOD;
        [Size(20)]
        public string TYPEBARCOD
        {
            get { return fTYPEBARCOD; }
            set { SetPropertyValue<string>(nameof(TYPEBARCOD), ref fTYPEBARCOD, value); }
        }
        string fLOGIN;
        [Size(20)]
        public string LOGIN
        {
            get { return fLOGIN; }
            set { SetPropertyValue<string>(nameof(LOGIN), ref fLOGIN, value); }
        }
        string fPASS;
        [Size(8)]
        public string PASS
        {
            get { return fPASS; }
            set { SetPropertyValue<string>(nameof(PASS), ref fPASS, value); }
        }
        string fCUSTOMERID;
        [Size(12)]
        public string CUSTOMERID
        {
            get { return fCUSTOMERID; }
            set { SetPropertyValue<string>(nameof(CUSTOMERID), ref fCUSTOMERID, value); }
        }
        string fTEL;
        [Size(15)]
        public string TEL
        {
            get { return fTEL; }
            set { SetPropertyValue<string>(nameof(TEL), ref fTEL, value); }
        }
        string fFAX;
        [Size(15)]
        public string FAX
        {
            get { return fFAX; }
            set { SetPropertyValue<string>(nameof(FAX), ref fFAX, value); }
        }
        string fBIK;
        [Size(15)]
        public string BIK
        {
            get { return fBIK; }
            set { SetPropertyValue<string>(nameof(BIK), ref fBIK, value); }
        }
        string fINN;
        [Size(15)]
        public string INN
        {
            get { return fINN; }
            set { SetPropertyValue<string>(nameof(INN), ref fINN, value); }
        }
        string fGLASS;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string GLASS
        {
            get { return fGLASS; }
            set { SetPropertyValue<string>(nameof(GLASS), ref fGLASS, value); }
        }
        string fZAL;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string ZAL
        {
            get { return fZAL; }
            set { SetPropertyValue<string>(nameof(ZAL), ref fZAL, value); }
        }
        string fFILM;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string FILM
        {
            get { return fFILM; }
            set { SetPropertyValue<string>(nameof(FILM), ref fFILM, value); }
        }
        string fLGPRIZ;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string LGPRIZ
        {
            get { return fLGPRIZ; }
            set { SetPropertyValue<string>(nameof(LGPRIZ), ref fLGPRIZ, value); }
        }
        string fKPP;
        [Size(15)]
        public string KPP
        {
            get { return fKPP; }
            set { SetPropertyValue<string>(nameof(KPP), ref fKPP, value); }
        }
        string fVIP;
        [Indexed(@"LOGIN", Name = @"CUSTOMER_IDX1")]
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string VIP
        {
            get { return fVIP; }
            set { SetPropertyValue<string>(nameof(VIP), ref fVIP, value); }
        }
        string fTYPECUSTOMER;
        [Size(1)]
        [ColumnDbDefaultValue("'A'")]
        public string TYPECUSTOMER
        {
            get { return fTYPECUSTOMER; }
            set { SetPropertyValue<string>(nameof(TYPECUSTOMER), ref fTYPECUSTOMER, value); }
        }
        string fKODCURRENCY;
        [Size(3)]
        public string KODCURRENCY
        {
            get { return fKODCURRENCY; }
            set { SetPropertyValue<string>(nameof(KODCURRENCY), ref fKODCURRENCY, value); }
        }
        string fKODCOUNTRY;
        [Size(3)]
        public string KODCOUNTRY
        {
            get { return fKODCOUNTRY; }
            set { SetPropertyValue<string>(nameof(KODCOUNTRY), ref fKODCOUNTRY, value); }
        }
        string fKODACTIVE;
        [Size(1)]
        [ColumnDbDefaultValue("'A'")]
        public string KODACTIVE
        {
            get { return fKODACTIVE; }
            set { SetPropertyValue<string>(nameof(KODACTIVE), ref fKODACTIVE, value); }
        }
        string fKODAGENT;
        [Size(1)]
        [ColumnDbDefaultValue("'1'")]
        public string KODAGENT
        {
            get { return fKODAGENT; }
            set { SetPropertyValue<string>(nameof(KODAGENT), ref fKODAGENT, value); }
        }
        string fSPEC;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string SPEC
        {
            get { return fSPEC; }
            set { SetPropertyValue<string>(nameof(SPEC), ref fSPEC, value); }
        }
        char fSPEC_ACCOUNTING;
        [ColumnDbDefaultValue("'F'")]
        public char SPEC_ACCOUNTING
        {
            get { return fSPEC_ACCOUNTING; }
            set { SetPropertyValue<char>(nameof(SPEC_ACCOUNTING), ref fSPEC_ACCOUNTING, value); }
        }
        [Association(@"CUSTReferencesCUSTOMER")]
        public XPCollection<CUST> CUSTs { get { return GetCollection<CUST>(nameof(CUSTs)); } }
        [Association(@"CUSTOMER_ADDRESSReferencesCUSTOMER")]
        public XPCollection<CUSTOMER_ADDRESS> CUSTOMER_ADDRESSs { get { return GetCollection<CUSTOMER_ADDRESS>(nameof(CUSTOMER_ADDRESSs)); } }
        [Association(@"CUSTOMER_CONTACTSReferencesCUSTOMER")]
        public XPCollection<CUSTOMER_CONTACTS> CUSTOMER_CONTACTSs { get { return GetCollection<CUSTOMER_CONTACTS>(nameof(CUSTOMER_CONTACTSs)); } }
        [Association(@"CUSTOMER_MESSAGE_EVENTSReferencesCUSTOMER")]
        public XPCollection<CUSTOMER_MESSAGE_EVENTS> CUSTOMER_MESSAGE_EVENTSs { get { return GetCollection<CUSTOMER_MESSAGE_EVENTS>(nameof(CUSTOMER_MESSAGE_EVENTSs)); } }
        [Association(@"DOGOVORReferencesCUSTOMER")]
        public XPCollection<DOGOVOR> DOGOVORs { get { return GetCollection<DOGOVOR>(nameof(DOGOVORs)); } }
        [Association(@"GLASSReferencesCUSTOMER")]
        public XPCollection<GLASS> GLASSes { get { return GetCollection<GLASS>(nameof(GLASSes)); } }
        [Association(@"ORDERReferencesCUSTOMER")]
        public XPCollection<ORDER> ORDERs { get { return GetCollection<ORDER>(nameof(ORDERs)); } }
        [Association(@"REGDOCReferencesCUSTOMER")]
        public XPCollection<REGDOC> REGDOCs { get { return GetCollection<REGDOC>(nameof(REGDOCs)); } }
    }

}
