//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_ADDRESS : XPLiteObject
    {
        string fKONTAKT;
        [Size(30)]
        public string KONTAKT
        {
            get { return fKONTAKT; }
            set { SetPropertyValue<string>(nameof(KONTAKT), ref fKONTAKT, value); }
        }
        int fADDRESS_ID;
        [Key]
        public int ADDRESS_ID
        {
            get { return fADDRESS_ID; }
            set { SetPropertyValue<int>(nameof(ADDRESS_ID), ref fADDRESS_ID, value); }
        }
        int fADDRESS_DISTANCE;
        [ColumnDbDefaultValue("0")]
        public int ADDRESS_DISTANCE
        {
            get { return fADDRESS_DISTANCE; }
            set { SetPropertyValue<int>(nameof(ADDRESS_DISTANCE), ref fADDRESS_DISTANCE, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Indexed(@"ADDRESS_NAME", Name = @"UNQ1_CUSTOMER_ADDRESS", Unique = true)]
        [Size(20)]
        [Association(@"CUSTOMER_ADDRESSReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        short fADDRESS_COUNTRY_SUBJECT;
        [ColumnDbDefaultValue("null")]
        public short ADDRESS_COUNTRY_SUBJECT
        {
            get { return fADDRESS_COUNTRY_SUBJECT; }
            set { SetPropertyValue<short>(nameof(ADDRESS_COUNTRY_SUBJECT), ref fADDRESS_COUNTRY_SUBJECT, value); }
        }
        short fADDRESS_DISTRICT;
        [ColumnDbDefaultValue("0")]
        public short ADDRESS_DISTRICT
        {
            get { return fADDRESS_DISTRICT; }
            set { SetPropertyValue<short>(nameof(ADDRESS_DISTRICT), ref fADDRESS_DISTRICT, value); }
        }
        string fADDRESS_NAME;
        [Size(200)]
        public string ADDRESS_NAME
        {
            get { return fADDRESS_NAME; }
            set { SetPropertyValue<string>(nameof(ADDRESS_NAME), ref fADDRESS_NAME, value); }
        }
        string fTEL;
        [Size(15)]
        public string TEL
        {
            get { return fTEL; }
            set { SetPropertyValue<string>(nameof(TEL), ref fTEL, value); }
        }
        [Association(@"CUSTReferencesCUSTOMER_ADDRESS")]
        public XPCollection<CUST> CUSTs { get { return GetCollection<CUST>(nameof(CUSTs)); } }
    }

}
