//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_PRICE : XPLiteObject
    {
        double fDELTA;
        [ColumnDbDefaultValue("0")]
        public double DELTA
        {
            get { return fDELTA; }
            set { SetPropertyValue<double>(nameof(DELTA), ref fDELTA, value); }
        }
        int fPRICEID;
        public int PRICEID
        {
            get { return fPRICEID; }
            set { SetPropertyValue<int>(nameof(PRICEID), ref fPRICEID, value); }
        }
        decimal fDISCOUNT;
        [ColumnDbDefaultValue("100")]
        public decimal DISCOUNT
        {
            get { return fDISCOUNT; }
            set { SetPropertyValue<decimal>(nameof(DISCOUNT), ref fDISCOUNT, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PRICETYPEID")]
            public int PRICETYPEID { get; set; }
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
