//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_CONTACTS : XPLiteObject
    {
        int fCONTACT_ID;
        [Key]
        public int CONTACT_ID
        {
            get { return fCONTACT_ID; }
            set { SetPropertyValue<int>(nameof(CONTACT_ID), ref fCONTACT_ID, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Size(20)]
        [Association(@"CUSTOMER_CONTACTSReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        short fCONTACT_TYPE;
        public short CONTACT_TYPE
        {
            get { return fCONTACT_TYPE; }
            set { SetPropertyValue<short>(nameof(CONTACT_TYPE), ref fCONTACT_TYPE, value); }
        }
        string fCONTACT;
        [Size(80)]
        public string CONTACT
        {
            get { return fCONTACT; }
            set { SetPropertyValue<string>(nameof(CONTACT), ref fCONTACT, value); }
        }
        string fSENDINVOICE;
        [Size(1)]
        [ColumnDbDefaultValue("0")]
        public string SENDINVOICE
        {
            get { return fSENDINVOICE; }
            set { SetPropertyValue<string>(nameof(SENDINVOICE), ref fSENDINVOICE, value); }
        }
        string fSENDWAYBILL;
        [Size(1)]
        [ColumnDbDefaultValue("0")]
        public string SENDWAYBILL
        {
            get { return fSENDWAYBILL; }
            set { SetPropertyValue<string>(nameof(SENDWAYBILL), ref fSENDWAYBILL, value); }
        }
        string fSENDWAYBILLSPEC;
        [Size(1)]
        [ColumnDbDefaultValue("0")]
        public string SENDWAYBILLSPEC
        {
            get { return fSENDWAYBILLSPEC; }
            set { SetPropertyValue<string>(nameof(SENDWAYBILLSPEC), ref fSENDWAYBILLSPEC, value); }
        }
    }

}
