//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_EVENTS_PERIODS : XPLiteObject
    {
        string fPERIOD_NAME;
        [Size(30)]
        public string PERIOD_NAME
        {
            get { return fPERIOD_NAME; }
            set { SetPropertyValue<string>(nameof(PERIOD_NAME), ref fPERIOD_NAME, value); }
        }
        int fPERIOD_ID;
        [Key]
        public int PERIOD_ID
        {
            get { return fPERIOD_ID; }
            set { SetPropertyValue<int>(nameof(PERIOD_ID), ref fPERIOD_ID, value); }
        }
        CUSTOMER_MESSAGE_EVENTS fCUSTOMER_EVENT_ID;
        [Association(@"CUSTOMER_EVENTS_PERIODSReferencesCUSTOMER_MESSAGE_EVENTS")]
        public CUSTOMER_MESSAGE_EVENTS CUSTOMER_EVENT_ID
        {
            get { return fCUSTOMER_EVENT_ID; }
            set { SetPropertyValue<CUSTOMER_MESSAGE_EVENTS>(nameof(CUSTOMER_EVENT_ID), ref fCUSTOMER_EVENT_ID, value); }
        }
        DateTime fPERIOD_BEG;
        public DateTime PERIOD_BEG
        {
            get { return fPERIOD_BEG; }
            set { SetPropertyValue<DateTime>(nameof(PERIOD_BEG), ref fPERIOD_BEG, value); }
        }
        DateTime fPERIOD_END;
        public DateTime PERIOD_END
        {
            get { return fPERIOD_END; }
            set { SetPropertyValue<DateTime>(nameof(PERIOD_END), ref fPERIOD_END, value); }
        }
        short fWEEKDAYS;
        public short WEEKDAYS
        {
            get { return fWEEKDAYS; }
            set { SetPropertyValue<short>(nameof(WEEKDAYS), ref fWEEKDAYS, value); }
        }
    }

}
