//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_MESSAGE_EVENTS : XPLiteObject
    {
        int fCUSTOMER_EVENT_ID;
        [Key]
        public int CUSTOMER_EVENT_ID
        {
            get { return fCUSTOMER_EVENT_ID; }
            set { SetPropertyValue<int>(nameof(CUSTOMER_EVENT_ID), ref fCUSTOMER_EVENT_ID, value); }
        }
        MESSAGE_EVENT_TYPES fEVENT_TYPE_ID;
        [Association(@"CUSTOMER_MESSAGE_EVENTSReferencesMESSAGE_EVENT_TYPES")]
        public MESSAGE_EVENT_TYPES EVENT_TYPE_ID
        {
            get { return fEVENT_TYPE_ID; }
            set { SetPropertyValue<MESSAGE_EVENT_TYPES>(nameof(EVENT_TYPE_ID), ref fEVENT_TYPE_ID, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Size(20)]
        [Association(@"CUSTOMER_MESSAGE_EVENTSReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        [Association(@"CUSTOMER_EVENTS_PERIODSReferencesCUSTOMER_MESSAGE_EVENTS")]
        public XPCollection<CUSTOMER_EVENTS_PERIODS> CUSTOMER_EVENTS_PERIODSs { get { return GetCollection<CUSTOMER_EVENTS_PERIODS>(nameof(CUSTOMER_EVENTS_PERIODSs)); } }
        [Association(@"MESSAGESReferencesCUSTOMER_MESSAGE_EVENTS")]
        public XPCollection<MESSAGES> MESSAGESCollection { get { return GetCollection<MESSAGES>(nameof(MESSAGESCollection)); } }
    }

}
