//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUSTOMER_MANAGER : XPLiteObject
    {
        string fFULLNAME;
        [Size(150)]
        public string FULLNAME
        {
            get { return fFULLNAME; }
            set { SetPropertyValue<string>(nameof(FULLNAME), ref fFULLNAME, value); }
        }
        int fMANAGERID;
        [Key]
        public int MANAGERID
        {
            get { return fMANAGERID; }
            set { SetPropertyValue<int>(nameof(MANAGERID), ref fMANAGERID, value); }
        }
        string fSHORTNAME;
        [Size(50)]
        public string SHORTNAME
        {
            get { return fSHORTNAME; }
            set { SetPropertyValue<string>(nameof(SHORTNAME), ref fSHORTNAME, value); }
        }
        string fEMAIL;
        [Size(50)]
        public string EMAIL
        {
            get { return fEMAIL; }
            set { SetPropertyValue<string>(nameof(EMAIL), ref fEMAIL, value); }
        }
        string fPHONE;
        [Size(40)]
        public string PHONE
        {
            get { return fPHONE; }
            set { SetPropertyValue<string>(nameof(PHONE), ref fPHONE, value); }
        }
        [Association(@"CUSTOMERReferencesCUSTOMER_MANAGER")]
        public XPCollection<CUSTOMER> CUSTOMERs { get { return GetCollection<CUSTOMER>(nameof(CUSTOMERs)); } }
    }

}
