//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class CUST : XPLiteObject
    {
        string fCUSTID;
        [Key]
        [Size(14)]
        public string CUSTID
        {
            get { return fCUSTID; }
            set { SetPropertyValue<string>(nameof(CUSTID), ref fCUSTID, value); }
        }
        DateTime fDATEINPUT;
        [Indexed(Name = @"IND_CUST_DATEINPUT")]
        public DateTime DATEINPUT
        {
            get { return fDATEINPUT; }
            set { SetPropertyValue<DateTime>(nameof(DATEINPUT), ref fDATEINPUT, value); }
        }
        DateTime fDATECUSTOMER;
        [Indexed(Name = @"IND_CUST_DATECUSTOMER")]
        public DateTime DATECUSTOMER
        {
            get { return fDATECUSTOMER; }
            set { SetPropertyValue<DateTime>(nameof(DATECUSTOMER), ref fDATECUSTOMER, value); }
        }
        DateTime fDATEWORK;
        [Indexed(Name = @"IND_CUST_DATEWORK")]
        public DateTime DATEWORK
        {
            get { return fDATEWORK; }
            set { SetPropertyValue<DateTime>(nameof(DATEWORK), ref fDATEWORK, value); }
        }
        double fPRICEFILM;
        public double PRICEFILM
        {
            get { return fPRICEFILM; }
            set { SetPropertyValue<double>(nameof(PRICEFILM), ref fPRICEFILM, value); }
        }
        double fPRICESPROS;
        public double PRICESPROS
        {
            get { return fPRICESPROS; }
            set { SetPropertyValue<double>(nameof(PRICESPROS), ref fPRICESPROS, value); }
        }
        double fPRICEZAL;
        public double PRICEZAL
        {
            get { return fPRICEZAL; }
            set { SetPropertyValue<double>(nameof(PRICEZAL), ref fPRICEZAL, value); }
        }
        double fPRICEGAS;
        public double PRICEGAS
        {
            get { return fPRICEGAS; }
            set { SetPropertyValue<double>(nameof(PRICEGAS), ref fPRICEGAS, value); }
        }
        double fPRICECALC;
        public double PRICECALC
        {
            get { return fPRICECALC; }
            set { SetPropertyValue<double>(nameof(PRICECALC), ref fPRICECALC, value); }
        }
        double fPRICECALC1;
        public double PRICECALC1
        {
            get { return fPRICECALC1; }
            set { SetPropertyValue<double>(nameof(PRICECALC1), ref fPRICECALC1, value); }
        }
        double fPRICECALC2;
        public double PRICECALC2
        {
            get { return fPRICECALC2; }
            set { SetPropertyValue<double>(nameof(PRICECALC2), ref fPRICECALC2, value); }
        }
        double fPRICEITOG;
        public double PRICEITOG
        {
            get { return fPRICEITOG; }
            set { SetPropertyValue<double>(nameof(PRICEITOG), ref fPRICEITOG, value); }
        }
        string fKOMGLASS;
        [Size(70)]
        public string KOMGLASS
        {
            get { return fKOMGLASS; }
            set { SetPropertyValue<string>(nameof(KOMGLASS), ref fKOMGLASS, value); }
        }
        double fSQU;
        public double SQU
        {
            get { return fSQU; }
            set { SetPropertyValue<double>(nameof(SQU), ref fSQU, value); }
        }
        double fFIXCENAM;
        public double FIXCENAM
        {
            get { return fFIXCENAM; }
            set { SetPropertyValue<double>(nameof(FIXCENAM), ref fFIXCENAM, value); }
        }
        DateTime fDATEREAL;
        [Indexed(Name = @"IND_CUST_DATEREAL")]
        public DateTime DATEREAL
        {
            get { return fDATEREAL; }
            set { SetPropertyValue<DateTime>(nameof(DATEREAL), ref fDATEREAL, value); }
        }
        DateTime fBIRTHDAY;
        public DateTime BIRTHDAY
        {
            get { return fBIRTHDAY; }
            set { SetPropertyValue<DateTime>(nameof(BIRTHDAY), ref fBIRTHDAY, value); }
        }
        DateTime fDTLASTEDIT;
        public DateTime DTLASTEDIT
        {
            get { return fDTLASTEDIT; }
            set { SetPropertyValue<DateTime>(nameof(DTLASTEDIT), ref fDTLASTEDIT, value); }
        }
        double fPRICERUN;
        [ColumnDbDefaultValue("0")]
        public double PRICERUN
        {
            get { return fPRICERUN; }
            set { SetPropertyValue<double>(nameof(PRICERUN), ref fPRICERUN, value); }
        }
        DateTime fDTOPEN;
        public DateTime DTOPEN
        {
            get { return fDTOPEN; }
            set { SetPropertyValue<DateTime>(nameof(DTOPEN), ref fDTOPEN, value); }
        }
        double fPRICECALC3;
        public double PRICECALC3
        {
            get { return fPRICECALC3; }
            set { SetPropertyValue<double>(nameof(PRICECALC3), ref fPRICECALC3, value); }
        }
        double fSQU_SPOP;
        [ColumnDbDefaultValue("0")]
        public double SQU_SPOP
        {
            get { return fSQU_SPOP; }
            set { SetPropertyValue<double>(nameof(SQU_SPOP), ref fSQU_SPOP, value); }
        }
        double fWEIGHT;
        [ColumnDbDefaultValue("0")]
        public double WEIGHT
        {
            get { return fWEIGHT; }
            set { SetPropertyValue<double>(nameof(WEIGHT), ref fWEIGHT, value); }
        }
        double fPRICEFRAME;
        [ColumnDbDefaultValue("0")]
        public double PRICEFRAME
        {
            get { return fPRICEFRAME; }
            set { SetPropertyValue<double>(nameof(PRICEFRAME), ref fPRICEFRAME, value); }
        }
        DateTime fDATEWORK_1C;
        public DateTime DATEWORK_1C
        {
            get { return fDATEWORK_1C; }
            set { SetPropertyValue<DateTime>(nameof(DATEWORK_1C), ref fDATEWORK_1C, value); }
        }
        int fCUSTNUMNF;
        [Indexed(Name = @"IND_CUST_CUSTNUMNF")]
        public int CUSTNUMNF
        {
            get { return fCUSTNUMNF; }
            set { SetPropertyValue<int>(nameof(CUSTNUMNF), ref fCUSTNUMNF, value); }
        }
        string fCUSTNUMCUSTOMER;
        [Size(50)]
        public string CUSTNUMCUSTOMER
        {
            get { return fCUSTNUMCUSTOMER; }
            set { SetPropertyValue<string>(nameof(CUSTNUMCUSTOMER), ref fCUSTNUMCUSTOMER, value); }
        }
        int fLGPR;
        [ColumnDbDefaultValue("0")]
        public int LGPR
        {
            get { return fLGPR; }
            set { SetPropertyValue<int>(nameof(LGPR), ref fLGPR, value); }
        }
        int fNUMFILMCUST;
        public int NUMFILMCUST
        {
            get { return fNUMFILMCUST; }
            set { SetPropertyValue<int>(nameof(NUMFILMCUST), ref fNUMFILMCUST, value); }
        }
        int fPOOL;
        public int POOL
        {
            get { return fPOOL; }
            set { SetPropertyValue<int>(nameof(POOL), ref fPOOL, value); }
        }
        int fTYPECALC;
        public int TYPECALC
        {
            get { return fTYPECALC; }
            set { SetPropertyValue<int>(nameof(TYPECALC), ref fTYPECALC, value); }
        }
        int fISTENDER;
        [ColumnDbDefaultValue("0")]
        public int ISTENDER
        {
            get { return fISTENDER; }
            set { SetPropertyValue<int>(nameof(ISTENDER), ref fISTENDER, value); }
        }
        int fISTENDERBRAK;
        [ColumnDbDefaultValue("0")]
        public int ISTENDERBRAK
        {
            get { return fISTENDERBRAK; }
            set { SetPropertyValue<int>(nameof(ISTENDERBRAK), ref fISTENDERBRAK, value); }
        }
        int fISOPEN;
        [ColumnDbDefaultValue("0")]
        public int ISOPEN
        {
            get { return fISOPEN; }
            set { SetPropertyValue<int>(nameof(ISOPEN), ref fISOPEN, value); }
        }
        int fDOGOVORID;
        [ColumnDbDefaultValue("null")]
        public int DOGOVORID
        {
            get { return fDOGOVORID; }
            set { SetPropertyValue<int>(nameof(DOGOVORID), ref fDOGOVORID, value); }
        }
        CUSTOMER_ADDRESS fADDRESSID;
        [Association(@"CUSTReferencesCUSTOMER_ADDRESS")]
        public CUSTOMER_ADDRESS ADDRESSID
        {
            get { return fADDRESSID; }
            set { SetPropertyValue<CUSTOMER_ADDRESS>(nameof(ADDRESSID), ref fADDRESSID, value); }
        }
        string fKOMENT;
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Size(20)]
        [Association(@"CUSTReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        short fGLASSCOUNT;
        public short GLASSCOUNT
        {
            get { return fGLASSCOUNT; }
            set { SetPropertyValue<short>(nameof(GLASSCOUNT), ref fGLASSCOUNT, value); }
        }
        short fPRIVGLASSCOUNT;
        public short PRIVGLASSCOUNT
        {
            get { return fPRIVGLASSCOUNT; }
            set { SetPropertyValue<short>(nameof(PRIVGLASSCOUNT), ref fPRIVGLASSCOUNT, value); }
        }
        CUSTSTATUS fSTATENUM;
        [ColumnDbDefaultValue("0")]
        [Association(@"CUSTReferencesCUSTSTATUS")]
        public CUSTSTATUS STATENUM
        {
            get { return fSTATENUM; }
            set { SetPropertyValue<CUSTSTATUS>(nameof(STATENUM), ref fSTATENUM, value); }
        }
        short fSTATE0;
        [ColumnDbDefaultValue("0")]
        public short STATE0
        {
            get { return fSTATE0; }
            set { SetPropertyValue<short>(nameof(STATE0), ref fSTATE0, value); }
        }
        short fSTATE1;
        [ColumnDbDefaultValue("0")]
        public short STATE1
        {
            get { return fSTATE1; }
            set { SetPropertyValue<short>(nameof(STATE1), ref fSTATE1, value); }
        }
        short fSTATE2;
        [ColumnDbDefaultValue("0")]
        public short STATE2
        {
            get { return fSTATE2; }
            set { SetPropertyValue<short>(nameof(STATE2), ref fSTATE2, value); }
        }
        short fSTATE3;
        [ColumnDbDefaultValue("0")]
        public short STATE3
        {
            get { return fSTATE3; }
            set { SetPropertyValue<short>(nameof(STATE3), ref fSTATE3, value); }
        }
        short fSTATE4;
        [ColumnDbDefaultValue("0")]
        public short STATE4
        {
            get { return fSTATE4; }
            set { SetPropertyValue<short>(nameof(STATE4), ref fSTATE4, value); }
        }
        short fSTATE5;
        [ColumnDbDefaultValue("0")]
        public short STATE5
        {
            get { return fSTATE5; }
            set { SetPropertyValue<short>(nameof(STATE5), ref fSTATE5, value); }
        }
        short fGRNUM;
        [Indexed(Name = @"IND_CUST_GRNUM")]
        [ColumnDbDefaultValue("0")]
        public short GRNUM
        {
            get { return fGRNUM; }
            set { SetPropertyValue<short>(nameof(GRNUM), ref fGRNUM, value); }
        }
        short fPGNUM;
        [ColumnDbDefaultValue("1")]
        public short PGNUM
        {
            get { return fPGNUM; }
            set { SetPropertyValue<short>(nameof(PGNUM), ref fPGNUM, value); }
        }
        string fSPIS;
        [Size(20)]
        public string SPIS
        {
            get { return fSPIS; }
            set { SetPropertyValue<string>(nameof(SPIS), ref fSPIS, value); }
        }
        string fADRESGRUZ;
        [Size(40)]
        public string ADRESGRUZ
        {
            get { return fADRESGRUZ; }
            set { SetPropertyValue<string>(nameof(ADRESGRUZ), ref fADRESGRUZ, value); }
        }
        PLATFORM fPLATFORM;
        [ColumnDbDefaultValue("0")]
        [Association(@"CUSTReferencesPLATFORM")]
        public PLATFORM PLATFORM
        {
            get { return fPLATFORM; }
            set { SetPropertyValue<PLATFORM>(nameof(PLATFORM), ref fPLATFORM, value); }
        }
        string fALIASDILER;
        [Size(20)]
        public string ALIASDILER
        {
            get { return fALIASDILER; }
            set { SetPropertyValue<string>(nameof(ALIASDILER), ref fALIASDILER, value); }
        }
        short fOPZSTYPE;
        public short OPZSTYPE
        {
            get { return fOPZSTYPE; }
            set { SetPropertyValue<short>(nameof(OPZSTYPE), ref fOPZSTYPE, value); }
        }
        string fBN;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string BN
        {
            get { return fBN; }
            set { SetPropertyValue<string>(nameof(BN), ref fBN, value); }
        }
        string fBRAK;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string BRAK
        {
            get { return fBRAK; }
            set { SetPropertyValue<string>(nameof(BRAK), ref fBRAK, value); }
        }
        string fFATHER;
        [Size(31)]
        [ColumnDbDefaultValue("'create'")]
        public string FATHER
        {
            get { return fFATHER; }
            set { SetPropertyValue<string>(nameof(FATHER), ref fFATHER, value); }
        }
        string fLASTEDITOR;
        [Size(31)]
        [ColumnDbDefaultValue("'create'")]
        public string LASTEDITOR
        {
            get { return fLASTEDITOR; }
            set { SetPropertyValue<string>(nameof(LASTEDITOR), ref fLASTEDITOR, value); }
        }
        string fBBUHTA;
        [Size(1)]
        [ColumnDbDefaultValue("'T'")]
        public string BBUHTA
        {
            get { return fBBUHTA; }
            set { SetPropertyValue<string>(nameof(BBUHTA), ref fBBUHTA, value); }
        }
        string fBARHIVE;
        [Size(1)]
        [ColumnDbDefaultValue("'T'")]
        public string BARHIVE
        {
            get { return fBARHIVE; }
            set { SetPropertyValue<string>(nameof(BARHIVE), ref fBARHIVE, value); }
        }
        string fBNV;
        [Size(1)]
        [ColumnDbDefaultValue("'T'")]
        public string BNV
        {
            get { return fBNV; }
            set { SetPropertyValue<string>(nameof(BNV), ref fBNV, value); }
        }
        string fB1C;
        [Size(1)]
        [ColumnDbDefaultValue("'T'")]
        public string B1C
        {
            get { return fB1C; }
            set { SetPropertyValue<string>(nameof(B1C), ref fB1C, value); }
        }
        string fOPENUSER;
        [Size(31)]
        public string OPENUSER
        {
            get { return fOPENUSER; }
            set { SetPropertyValue<string>(nameof(OPENUSER), ref fOPENUSER, value); }
        }
        [Association(@"MESSAGESReferencesCUST")]
        public XPCollection<MESSAGES> MESSAGESCollection { get { return GetCollection<MESSAGES>(nameof(MESSAGESCollection)); } }
    }

}
