//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class DOGOVOR : XPLiteObject
    {
        DateTime fDATEBEGIN;
        public DateTime DATEBEGIN
        {
            get { return fDATEBEGIN; }
            set { SetPropertyValue<DateTime>(nameof(DATEBEGIN), ref fDATEBEGIN, value); }
        }
        DateTime fDATEEND;
        public DateTime DATEEND
        {
            get { return fDATEEND; }
            set { SetPropertyValue<DateTime>(nameof(DATEEND), ref fDATEEND, value); }
        }
        int fDGRID;
        [Key]
        public int DGRID
        {
            get { return fDGRID; }
            set { SetPropertyValue<int>(nameof(DGRID), ref fDGRID, value); }
        }
        int fDOGOVORNUM;
        [ColumnDbDefaultValue("0")]
        public int DOGOVORNUM
        {
            get { return fDOGOVORNUM; }
            set { SetPropertyValue<int>(nameof(DOGOVORNUM), ref fDOGOVORNUM, value); }
        }
        CUSTOMER fCUSTOMER;
        [Size(20)]
        [Association(@"DOGOVORReferencesCUSTOMER")]
        public CUSTOMER CUSTOMER
        {
            get { return fCUSTOMER; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMER), ref fCUSTOMER, value); }
        }
        string fDOGOVORNAME;
        public string DOGOVORNAME
        {
            get { return fDOGOVORNAME; }
            set { SetPropertyValue<string>(nameof(DOGOVORNAME), ref fDOGOVORNAME, value); }
        }
    }

}
