//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FIGURECOORD : XPLiteObject
    {
        string fID;
        [Key]
        [Size(10)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        string fFORMULA;
        [Size(300)]
        [ColumnDbDefaultValue("'0'")]
        public string FORMULA
        {
            get { return fFORMULA; }
            set { SetPropertyValue<string>(nameof(FORMULA), ref fFORMULA, value); }
        }
        FORMPARAM fFORMALIAS;
        [Size(3)]
        [Association(@"FIGURECOORDReferencesFORMPARAM")]
        public FORMPARAM FORMALIAS
        {
            get { return fFORMALIAS; }
            set { SetPropertyValue<FORMPARAM>(nameof(FORMALIAS), ref fFORMALIAS, value); }
        }
        string fTGBSIZE;
        [Size(1)]
        public string TGBSIZE
        {
            get { return fTGBSIZE; }
            set { SetPropertyValue<string>(nameof(TGBSIZE), ref fTGBSIZE, value); }
        }
    }

}
