//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FIGURE : XPLiteObject
    {
        string fID;
        [Key]
        [Size(10)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        FIGURE fFIGURE_ID;
        [Size(10)]
        [Association(@"FIGUREReferencesFIGURE")]
        public FIGURE FIGURE_ID
        {
            get { return fFIGURE_ID; }
            set { SetPropertyValue<FIGURE>(nameof(FIGURE_ID), ref fFIGURE_ID, value); }
        }
        FORMPARAM fFORMALIAS;
        [Size(3)]
        [Association(@"FIGUREReferencesFORMPARAM")]
        public FORMPARAM FORMALIAS
        {
            get { return fFORMALIAS; }
            set { SetPropertyValue<FORMPARAM>(nameof(FORMALIAS), ref fFORMALIAS, value); }
        }
        [Association(@"FIGUREReferencesFIGURE")]
        public XPCollection<FIGURE> FIGURECollection { get { return GetCollection<FIGURE>(nameof(FIGURECollection)); } }
    }

}
