//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FILMTYPE : XPLiteObject
    {
        string fFILMTYPENAME;
        [Size(70)]
        public string FILMTYPENAME
        {
            get { return fFILMTYPENAME; }
            set { SetPropertyValue<string>(nameof(FILMTYPENAME), ref fFILMTYPENAME, value); }
        }
        int fFILMTYPEID;
        [Key]
        public int FILMTYPEID
        {
            get { return fFILMTYPEID; }
            set { SetPropertyValue<int>(nameof(FILMTYPEID), ref fFILMTYPEID, value); }
        }
        [Association(@"FILMSReferencesFILMTYPE")]
        public XPCollection<FILMS> FILMSCollection { get { return GetCollection<FILMS>(nameof(FILMSCollection)); } }
    }

}
