//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FILMS : XPLiteObject
    {
        double fROLLWIDTH;
        public double ROLLWIDTH
        {
            get { return fROLLWIDTH; }
            set { SetPropertyValue<double>(nameof(ROLLWIDTH), ref fROLLWIDTH, value); }
        }
        string fFILMCOLOR;
        [Size(30)]
        public string FILMCOLOR
        {
            get { return fFILMCOLOR; }
            set { SetPropertyValue<string>(nameof(FILMCOLOR), ref fFILMCOLOR, value); }
        }
        FILMTYPE fFILMTYPE;
        [Association(@"FILMSReferencesFILMTYPE")]
        public FILMTYPE FILMTYPE
        {
            get { return fFILMTYPE; }
            set { SetPropertyValue<FILMTYPE>(nameof(FILMTYPE), ref fFILMTYPE, value); }
        }
        string fGOSTMARK;
        [Size(10)]
        public string GOSTMARK
        {
            get { return fGOSTMARK; }
            set { SetPropertyValue<string>(nameof(GOSTMARK), ref fGOSTMARK, value); }
        }
        string fFILMNAME;
        [Key]
        [Size(20)]
        public string FILMNAME
        {
            get { return fFILMNAME; }
            set { SetPropertyValue<string>(nameof(FILMNAME), ref fFILMNAME, value); }
        }
        string fFILMID_1C;
        [Size(20)]
        [ColumnDbDefaultValue("'3800'")]
        public string FILMID_1C
        {
            get { return fFILMID_1C; }
            set { SetPropertyValue<string>(nameof(FILMID_1C), ref fFILMID_1C, value); }
        }
    }

}
