//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FORM : XPLiteObject
    {
        DateTime fDT_EDIT;
        [ColumnDbDefaultValue("current_timestamp\r\n")]
        public DateTime DT_EDIT
        {
            get { return fDT_EDIT; }
            set { SetPropertyValue<DateTime>(nameof(DT_EDIT), ref fDT_EDIT, value); }
        }
        string fFORMNAME;
        [Size(20)]
        public string FORMNAME
        {
            get { return fFORMNAME; }
            set { SetPropertyValue<string>(nameof(FORMNAME), ref fFORMNAME, value); }
        }
        short fPRICE0;
        public short PRICE0
        {
            get { return fPRICE0; }
            set { SetPropertyValue<short>(nameof(PRICE0), ref fPRICE0, value); }
        }
        short fPRICE1;
        public short PRICE1
        {
            get { return fPRICE1; }
            set { SetPropertyValue<short>(nameof(PRICE1), ref fPRICE1, value); }
        }
        short fPRICE2;
        public short PRICE2
        {
            get { return fPRICE2; }
            set { SetPropertyValue<short>(nameof(PRICE2), ref fPRICE2, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
            [Size(3)]
            [Persistent("FORMALIAS")]
            public string FORMALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
