//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FORMCATALOG : XPLiteObject
    {
        int fCATALOGID;
        [Key]
        public int CATALOGID
        {
            get { return fCATALOGID; }
            set { SetPropertyValue<int>(nameof(CATALOGID), ref fCATALOGID, value); }
        }
        string fCATALOGNAME;
        [Size(20)]
        public string CATALOGNAME
        {
            get { return fCATALOGNAME; }
            set { SetPropertyValue<string>(nameof(CATALOGNAME), ref fCATALOGNAME, value); }
        }
    }

}
