//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FORMPARAM : XPLiteObject
    {
        string fDLLNAME;
        [Size(10)]
        public string DLLNAME
        {
            get { return fDLLNAME; }
            set { SetPropertyValue<string>(nameof(DLLNAME), ref fDLLNAME, value); }
        }
        string fDEFPARAMSTR;
        [Size(200)]
        public string DEFPARAMSTR
        {
            get { return fDEFPARAMSTR; }
            set { SetPropertyValue<string>(nameof(DEFPARAMSTR), ref fDEFPARAMSTR, value); }
        }
        string fDESCRIPTION;
        [Size(200)]
        public string DESCRIPTION
        {
            get { return fDESCRIPTION; }
            set { SetPropertyValue<string>(nameof(DESCRIPTION), ref fDESCRIPTION, value); }
        }
        string fIMGNAME;
        [Size(20)]
        public string IMGNAME
        {
            get { return fIMGNAME; }
            set { SetPropertyValue<string>(nameof(IMGNAME), ref fIMGNAME, value); }
        }
        string fFORMALIAS;
        [Key]
        [Size(3)]
        public string FORMALIAS
        {
            get { return fFORMALIAS; }
            set { SetPropertyValue<string>(nameof(FORMALIAS), ref fFORMALIAS, value); }
        }
        [Association(@"FIGUREReferencesFORMPARAM")]
        public XPCollection<FIGURE> FIGUREs { get { return GetCollection<FIGURE>(nameof(FIGUREs)); } }
        [Association(@"FIGURECOORDReferencesFORMPARAM")]
        public XPCollection<FIGURECOORD> FIGURECOORDs { get { return GetCollection<FIGURECOORD>(nameof(FIGURECOORDs)); } }
        [Association(@"FORMCHECKReferencesFORMPARAM")]
        public XPCollection<FORMCHECK> FORMCHECKs { get { return GetCollection<FORMCHECK>(nameof(FORMCHECKs)); } }
    }

}
