//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FORMCHECK : XPLiteObject
    {
        string fID;
        [Key]
        [Size(10)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        int fENABLED;
        [ColumnDbDefaultValue("1")]
        public int ENABLED
        {
            get { return fENABLED; }
            set { SetPropertyValue<int>(nameof(ENABLED), ref fENABLED, value); }
        }
        FORMPARAM fFORMALIAS;
        [Size(3)]
        [Association(@"FORMCHECKReferencesFORMPARAM")]
        public FORMPARAM FORMALIAS
        {
            get { return fFORMALIAS; }
            set { SetPropertyValue<FORMPARAM>(nameof(FORMALIAS), ref fFORMALIAS, value); }
        }
        string fCONDITION;
        [Size(255)]
        public string CONDITION
        {
            get { return fCONDITION; }
            set { SetPropertyValue<string>(nameof(CONDITION), ref fCONDITION, value); }
        }
        string fMSG_TRUE;
        [Size(255)]
        public string MSG_TRUE
        {
            get { return fMSG_TRUE; }
            set { SetPropertyValue<string>(nameof(MSG_TRUE), ref fMSG_TRUE, value); }
        }
        string fMSG_FALSE;
        [Size(255)]
        public string MSG_FALSE
        {
            get { return fMSG_FALSE; }
            set { SetPropertyValue<string>(nameof(MSG_FALSE), ref fMSG_FALSE, value); }
        }
    }

}
