//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class FRAME_TYPE : XPLiteObject
    {
        string fFRAME_TYPE_NAME;
        [Size(50)]
        public string FRAME_TYPE_NAME
        {
            get { return fFRAME_TYPE_NAME; }
            set { SetPropertyValue<string>(nameof(FRAME_TYPE_NAME), ref fFRAME_TYPE_NAME, value); }
        }
        string fPRINTMARK;
        [Size(20)]
        public string PRINTMARK
        {
            get { return fPRINTMARK; }
            set { SetPropertyValue<string>(nameof(PRINTMARK), ref fPRINTMARK, value); }
        }
        string fPRINTFRAME;
        [Size(20)]
        public string PRINTFRAME
        {
            get { return fPRINTFRAME; }
            set { SetPropertyValue<string>(nameof(PRINTFRAME), ref fPRINTFRAME, value); }
        }
        short fFRCODEMAT;
        [ColumnDbDefaultValue("0")]
        public short FRCODEMAT
        {
            get { return fFRCODEMAT; }
            set { SetPropertyValue<short>(nameof(FRCODEMAT), ref fFRCODEMAT, value); }
        }
        string fFRAMETYPE;
        [Key]
        [Size(5)]
        public string FRAMETYPE
        {
            get { return fFRAMETYPE; }
            set { SetPropertyValue<string>(nameof(FRAMETYPE), ref fFRAMETYPE, value); }
        }
    }

}
