//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASSPROCESSINGTYPE : XPLiteObject
    {
        double fMAXDAYSUM;
        [ColumnDbDefaultValue("0")]
        public double MAXDAYSUM
        {
            get { return fMAXDAYSUM; }
            set { SetPropertyValue<double>(nameof(MAXDAYSUM), ref fMAXDAYSUM, value); }
        }
        int fPROCTYPEID;
        [Key]
        public int PROCTYPEID
        {
            get { return fPROCTYPEID; }
            set { SetPropertyValue<int>(nameof(PROCTYPEID), ref fPROCTYPEID, value); }
        }
        string fPROCTYPENAME;
        [Size(50)]
        public string PROCTYPENAME
        {
            get { return fPROCTYPENAME; }
            set { SetPropertyValue<string>(nameof(PROCTYPENAME), ref fPROCTYPENAME, value); }
        }
        int fSTEP;
        [ColumnDbDefaultValue("0")]
        public int STEP
        {
            get { return fSTEP; }
            set { SetPropertyValue<int>(nameof(STEP), ref fSTEP, value); }
        }
        int fTPRCOLOR;
        [ColumnDbDefaultValue("0")]
        public int TPRCOLOR
        {
            get { return fTPRCOLOR; }
            set { SetPropertyValue<int>(nameof(TPRCOLOR), ref fTPRCOLOR, value); }
        }
        short fONEINGR;
        [ColumnDbDefaultValue("0")]
        public short ONEINGR
        {
            get { return fONEINGR; }
            set { SetPropertyValue<short>(nameof(ONEINGR), ref fONEINGR, value); }
        }
        short fALLINDAY;
        [ColumnDbDefaultValue("0")]
        public short ALLINDAY
        {
            get { return fALLINDAY; }
            set { SetPropertyValue<short>(nameof(ALLINDAY), ref fALLINDAY, value); }
        }
        string fTPRSHORTNAME;
        [Size(5)]
        public string TPRSHORTNAME
        {
            get { return fTPRSHORTNAME; }
            set { SetPropertyValue<string>(nameof(TPRSHORTNAME), ref fTPRSHORTNAME, value); }
        }
        [Association(@"GLASSPROCESSINGReferencesGLASSPROCESSINGTYPE")]
        public XPCollection<GLASSPROCESSING> GLASSPROCESSINGs { get { return GetCollection<GLASSPROCESSING>(nameof(GLASSPROCESSINGs)); } }
    }

}
