//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASSPROCESSING : XPLiteObject
    {
        int fPROCID;
        [Key]
        public int PROCID
        {
            get { return fPROCID; }
            set { SetPropertyValue<int>(nameof(PROCID), ref fPROCID, value); }
        }
        int fSIZEOUTCROP;
        [ColumnDbDefaultValue("0")]
        public int SIZEOUTCROP
        {
            get { return fSIZEOUTCROP; }
            set { SetPropertyValue<int>(nameof(SIZEOUTCROP), ref fSIZEOUTCROP, value); }
        }
        int fMINDELAY;
        public int MINDELAY
        {
            get { return fMINDELAY; }
            set { SetPropertyValue<int>(nameof(MINDELAY), ref fMINDELAY, value); }
        }
        int fMAXDELAY;
        public int MAXDELAY
        {
            get { return fMAXDELAY; }
            set { SetPropertyValue<int>(nameof(MAXDELAY), ref fMAXDELAY, value); }
        }
        GLASSPROCESSINGTYPE fPROCTYPE;
        [Association(@"GLASSPROCESSINGReferencesGLASSPROCESSINGTYPE")]
        public GLASSPROCESSINGTYPE PROCTYPE
        {
            get { return fPROCTYPE; }
            set { SetPropertyValue<GLASSPROCESSINGTYPE>(nameof(PROCTYPE), ref fPROCTYPE, value); }
        }
        int fPROCCOLOR;
        [ColumnDbDefaultValue("0")]
        public int PROCCOLOR
        {
            get { return fPROCCOLOR; }
            set { SetPropertyValue<int>(nameof(PROCCOLOR), ref fPROCCOLOR, value); }
        }
        string fSLOZNAME;
        [Size(10)]
        public string SLOZNAME
        {
            get { return fSLOZNAME; }
            set { SetPropertyValue<string>(nameof(SLOZNAME), ref fSLOZNAME, value); }
        }
        string fSTEPPREFID;
        [Size(2)]
        public string STEPPREFID
        {
            get { return fSTEPPREFID; }
            set { SetPropertyValue<string>(nameof(STEPPREFID), ref fSTEPPREFID, value); }
        }
        string fPROCNAME;
        [Size(20)]
        public string PROCNAME
        {
            get { return fPROCNAME; }
            set { SetPropertyValue<string>(nameof(PROCNAME), ref fPROCNAME, value); }
        }
        short fSTEP;
        [ColumnDbDefaultValue("0")]
        public short STEP
        {
            get { return fSTEP; }
            set { SetPropertyValue<short>(nameof(STEP), ref fSTEP, value); }
        }
        short fSPTYPE;
        public short SPTYPE
        {
            get { return fSPTYPE; }
            set { SetPropertyValue<short>(nameof(SPTYPE), ref fSPTYPE, value); }
        }
        string fCID_1C;
        [Size(20)]
        public string CID_1C
        {
            get { return fCID_1C; }
            set { SetPropertyValue<string>(nameof(CID_1C), ref fCID_1C, value); }
        }
        short fDAYSTEP;
        [ColumnDbDefaultValue("0")]
        public short DAYSTEP
        {
            get { return fDAYSTEP; }
            set { SetPropertyValue<short>(nameof(DAYSTEP), ref fDAYSTEP, value); }
        }
        short fTYPEOUTCROP;
        [ColumnDbDefaultValue("0")]
        public short TYPEOUTCROP
        {
            get { return fTYPEOUTCROP; }
            set { SetPropertyValue<short>(nameof(TYPEOUTCROP), ref fTYPEOUTCROP, value); }
        }
        short fISAUTO;
        [ColumnDbDefaultValue("0")]
        public short ISAUTO
        {
            get { return fISAUTO; }
            set { SetPropertyValue<short>(nameof(ISAUTO), ref fISAUTO, value); }
        }
        string fSHORTNAME;
        [Size(5)]
        public string SHORTNAME
        {
            get { return fSHORTNAME; }
            set { SetPropertyValue<string>(nameof(SHORTNAME), ref fSHORTNAME, value); }
        }
    }

}
