//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASSNOM : XPLiteObject
    {
        int fGLASSID;
        [Indexed(Name = @"UNQ1_GLASSNOM", Unique = true)]
        public int GLASSID
        {
            get { return fGLASSID; }
            set { SetPropertyValue<int>(nameof(GLASSID), ref fGLASSID, value); }
        }
        string fGLASSID_1C;
        [Size(20)]
        public string GLASSID_1C
        {
            get { return fGLASSID_1C; }
            set { SetPropertyValue<string>(nameof(GLASSID_1C), ref fGLASSID_1C, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("THICKNESS")]
            public int THICKNESS { get; set; }
            [Persistent("SELFGLASS")]
            public short SELFGLASS { get; set; }
            [Size(5)]
            [Persistent("GLASS")]
            public string GLASS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
