//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASSTYPE : XPLiteObject
    {
        string fGLASSTYPENAME;
        [Key]
        [Size(10)]
        public string GLASSTYPENAME
        {
            get { return fGLASSTYPENAME; }
            set { SetPropertyValue<string>(nameof(GLASSTYPENAME), ref fGLASSTYPENAME, value); }
        }
        string fGLASSNAME;
        [Indexed(Name = @"UNQ1_GLASSTYPE", Unique = true)]
        [Size(50)]
        public string GLASSNAME
        {
            get { return fGLASSNAME; }
            set { SetPropertyValue<string>(nameof(GLASSNAME), ref fGLASSNAME, value); }
        }
        string fGLASSSELECT;
        [Size(5)]
        public string GLASSSELECT
        {
            get { return fGLASSSELECT; }
            set { SetPropertyValue<string>(nameof(GLASSSELECT), ref fGLASSSELECT, value); }
        }
        [Association(@"GLASSReferencesGLASSTYPE")]
        public XPCollection<GLASS> GLASSes { get { return GetCollection<GLASS>(nameof(GLASSes)); } }
    }

}
