//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASS_STRUCTURE : XPLiteObject
    {
        int fSTRUCTUREID;
        [Key]
        public int STRUCTUREID
        {
            get { return fSTRUCTUREID; }
            set { SetPropertyValue<int>(nameof(STRUCTUREID), ref fSTRUCTUREID, value); }
        }
        string fSTRUCTURENAME;
        [Size(50)]
        public string STRUCTURENAME
        {
            get { return fSTRUCTURENAME; }
            set { SetPropertyValue<string>(nameof(STRUCTURENAME), ref fSTRUCTURENAME, value); }
        }
        string fSTRUCTURESHORTNAME;
        [Size(5)]
        public string STRUCTURESHORTNAME
        {
            get { return fSTRUCTURESHORTNAME; }
            set { SetPropertyValue<string>(nameof(STRUCTURESHORTNAME), ref fSTRUCTURESHORTNAME, value); }
        }
        [Association(@"GLASSReferencesGLASS_STRUCTURE")]
        public XPCollection<GLASS> GLASSes { get { return GetCollection<GLASS>(nameof(GLASSes)); } }
    }

}
