//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GLASS : XPLiteObject
    {
        GLASSTYPE fGLASSTYPE;
        [Size(10)]
        [Association(@"GLASSReferencesGLASSTYPE")]
        public GLASSTYPE GLASSTYPE
        {
            get { return fGLASSTYPE; }
            set { SetPropertyValue<GLASSTYPE>(nameof(GLASSTYPE), ref fGLASSTYPE, value); }
        }
        string fGOSTMARK;
        [Size(10)]
        public string GOSTMARK
        {
            get { return fGOSTMARK; }
            set { SetPropertyValue<string>(nameof(GOSTMARK), ref fGOSTMARK, value); }
        }
        string fCOLOR;
        [Size(50)]
        public string COLOR
        {
            get { return fCOLOR; }
            set { SetPropertyValue<string>(nameof(COLOR), ref fCOLOR, value); }
        }
        string fGLASSNAME;
        [Size(40)]
        public string GLASSNAME
        {
            get { return fGLASSNAME; }
            set { SetPropertyValue<string>(nameof(GLASSNAME), ref fGLASSNAME, value); }
        }
        GLASS_STRUCTURE fSTRUCTURE;
        [ColumnDbDefaultValue("0")]
        [Association(@"GLASSReferencesGLASS_STRUCTURE")]
        public GLASS_STRUCTURE STRUCTURE
        {
            get { return fSTRUCTURE; }
            set { SetPropertyValue<GLASS_STRUCTURE>(nameof(STRUCTURE), ref fSTRUCTURE, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Size(20)]
        [Association(@"GLASSReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        string fSHORTNAME;
        [Key]
        [Size(5)]
        public string SHORTNAME
        {
            get { return fSHORTNAME; }
            set { SetPropertyValue<string>(nameof(SHORTNAME), ref fSHORTNAME, value); }
        }
        GLASS fBASEGLASS;
        [Size(5)]
        [Association(@"GLASSReferencesGLASS")]
        public GLASS BASEGLASS
        {
            get { return fBASEGLASS; }
            set { SetPropertyValue<GLASS>(nameof(BASEGLASS), ref fBASEGLASS, value); }
        }
        [Association(@"GLASSReferencesGLASS")]
        public XPCollection<GLASS> GLASSCollection { get { return GetCollection<GLASS>(nameof(GLASSCollection)); } }
    }

}
