//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class GRNOM : XPLiteObject
    {
        string fNAMEGR;
        [Size(50)]
        public string NAMEGR
        {
            get { return fNAMEGR; }
            set { SetPropertyValue<string>(nameof(NAMEGR), ref fNAMEGR, value); }
        }
        string fALIASGR;
        [Key]
        [Size(5)]
        public string ALIASGR
        {
            get { return fALIASGR; }
            set { SetPropertyValue<string>(nameof(ALIASGR), ref fALIASGR, value); }
        }
    }

}
