//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class KURS : XPLiteObject
    {
        DateTime fDAT;
        [Key]
        public DateTime DAT
        {
            get { return fDAT; }
            set { SetPropertyValue<DateTime>(nameof(DAT), ref fDAT, value); }
        }
        double fVAL;
        public double VAL
        {
            get { return fVAL; }
            set { SetPropertyValue<double>(nameof(VAL), ref fVAL, value); }
        }
    }

}
