//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class LIMIT : XPLiteObject
    {
        int fPRIMARYLIMIT;
        public int PRIMARYLIMIT
        {
            get { return fPRIMARYLIMIT; }
            set { SetPropertyValue<int>(nameof(PRIMARYLIMIT), ref fPRIMARYLIMIT, value); }
        }
        int fSECONDARYLIMIT;
        public int SECONDARYLIMIT
        {
            get { return fSECONDARYLIMIT; }
            set { SetPropertyValue<int>(nameof(SECONDARYLIMIT), ref fSECONDARYLIMIT, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("DATEWORK")]
            public DateTime DATEWORK { get; set; }
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
            [Persistent("PLATFORM")]
            public short PLATFORM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
