//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class LINE : XPLiteObject
    {
        int fLINENUM;
        public int LINENUM
        {
            get { return fLINENUM; }
            set { SetPropertyValue<int>(nameof(LINENUM), ref fLINENUM, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("DATEWORK")]
            public DateTime DATEWORK { get; set; }
            [Persistent("PLATFORM")]
            public int PLATFORM { get; set; }
            [Persistent("GRNUM")]
            public int GRNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
