//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class LONGTEXTZURNAL : XPLiteObject
    {
        string fTXT;
        [Size(256)]
        public string TXT
        {
            get { return fTXT; }
            set { SetPropertyValue<string>(nameof(TXT), ref fTXT, value); }
        }
        string fID;
        [Key]
        [Size(3)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
    }

}
