//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class MESSAGES : XPLiteObject
    {
        long fMESSAGE_ID;
        [Key]
        public long MESSAGE_ID
        {
            get { return fMESSAGE_ID; }
            set { SetPropertyValue<long>(nameof(MESSAGE_ID), ref fMESSAGE_ID, value); }
        }
        CUST fCUSTID;
        [Size(14)]
        [Association(@"MESSAGESReferencesCUST")]
        public CUST CUSTID
        {
            get { return fCUSTID; }
            set { SetPropertyValue<CUST>(nameof(CUSTID), ref fCUSTID, value); }
        }
        DateTime fMESSAGE_DATE;
        public DateTime MESSAGE_DATE
        {
            get { return fMESSAGE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(MESSAGE_DATE), ref fMESSAGE_DATE, value); }
        }
        DateTime fMESSAGE_SEND_DATE;
        public DateTime MESSAGE_SEND_DATE
        {
            get { return fMESSAGE_SEND_DATE; }
            set { SetPropertyValue<DateTime>(nameof(MESSAGE_SEND_DATE), ref fMESSAGE_SEND_DATE, value); }
        }
        string fSENDING_RESULT;
        [Size(30)]
        public string SENDING_RESULT
        {
            get { return fSENDING_RESULT; }
            set { SetPropertyValue<string>(nameof(SENDING_RESULT), ref fSENDING_RESULT, value); }
        }
        CUSTOMER_MESSAGE_EVENTS fCUSTOMER_EVENT_ID;
        [Association(@"MESSAGESReferencesCUSTOMER_MESSAGE_EVENTS")]
        public CUSTOMER_MESSAGE_EVENTS CUSTOMER_EVENT_ID
        {
            get { return fCUSTOMER_EVENT_ID; }
            set { SetPropertyValue<CUSTOMER_MESSAGE_EVENTS>(nameof(CUSTOMER_EVENT_ID), ref fCUSTOMER_EVENT_ID, value); }
        }
        short fMESSAGE_STATUS;
        public short MESSAGE_STATUS
        {
            get { return fMESSAGE_STATUS; }
            set { SetPropertyValue<short>(nameof(MESSAGE_STATUS), ref fMESSAGE_STATUS, value); }
        }
        short fNOTIFY_OBJECT;
        public short NOTIFY_OBJECT
        {
            get { return fNOTIFY_OBJECT; }
            set { SetPropertyValue<short>(nameof(NOTIFY_OBJECT), ref fNOTIFY_OBJECT, value); }
        }
    }

}
