//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class MESSAGE_EVENT_TYPES : XPLiteObject
    {
        string fEVENT_TYPE_NAME;
        [Size(70)]
        public string EVENT_TYPE_NAME
        {
            get { return fEVENT_TYPE_NAME; }
            set { SetPropertyValue<string>(nameof(EVENT_TYPE_NAME), ref fEVENT_TYPE_NAME, value); }
        }
        int fEVENT_TYPE_ID;
        [Key]
        public int EVENT_TYPE_ID
        {
            get { return fEVENT_TYPE_ID; }
            set { SetPropertyValue<int>(nameof(EVENT_TYPE_ID), ref fEVENT_TYPE_ID, value); }
        }
        string fMESSAGE_SUBJECT;
        public string MESSAGE_SUBJECT
        {
            get { return fMESSAGE_SUBJECT; }
            set { SetPropertyValue<string>(nameof(MESSAGE_SUBJECT), ref fMESSAGE_SUBJECT, value); }
        }
        string fMESSAGE_SALUT;
        public string MESSAGE_SALUT
        {
            get { return fMESSAGE_SALUT; }
            set { SetPropertyValue<string>(nameof(MESSAGE_SALUT), ref fMESSAGE_SALUT, value); }
        }
        string fMESSAGE_TEXT;
        [Size(300)]
        public string MESSAGE_TEXT
        {
            get { return fMESSAGE_TEXT; }
            set { SetPropertyValue<string>(nameof(MESSAGE_TEXT), ref fMESSAGE_TEXT, value); }
        }
        string fMESSAGE_SIGN;
        public string MESSAGE_SIGN
        {
            get { return fMESSAGE_SIGN; }
            set { SetPropertyValue<string>(nameof(MESSAGE_SIGN), ref fMESSAGE_SIGN, value); }
        }
        [Association(@"CUSTOMER_MESSAGE_EVENTSReferencesMESSAGE_EVENT_TYPES")]
        public XPCollection<CUSTOMER_MESSAGE_EVENTS> CUSTOMER_MESSAGE_EVENTSs { get { return GetCollection<CUSTOMER_MESSAGE_EVENTS>(nameof(CUSTOMER_MESSAGE_EVENTSs)); } }
    }

}
