//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class NOMS : XPLiteObject
    {
        string fNOMID;
        [Size(14)]
        public string NOMID
        {
            get { return fNOMID; }
            set { SetPropertyValue<string>(nameof(NOMID), ref fNOMID, value); }
        }
        string fKOMENT;
        [Size(50)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        string fNAMENOM;
        [Size(50)]
        public string NAMENOM
        {
            get { return fNAMENOM; }
            set { SetPropertyValue<string>(nameof(NAMENOM), ref fNAMENOM, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("ALIASNOM")]
            public string ALIASNOM { get; set; }
            [Size(5)]
            [Persistent("ALIASGR")]
            public string ALIASGR { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
