//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class NORMSPIS : XPLiteObject
    {
        double fNORMATIV;
        public double NORMATIV
        {
            get { return fNORMATIV; }
            set { SetPropertyValue<double>(nameof(NORMATIV), ref fNORMATIV, value); }
        }
        string fALIASSOURCE;
        [Size(20)]
        public string ALIASSOURCE
        {
            get { return fALIASSOURCE; }
            set { SetPropertyValue<string>(nameof(ALIASSOURCE), ref fALIASSOURCE, value); }
        }
        string fALIASTARGET;
        [Size(20)]
        public string ALIASTARGET
        {
            get { return fALIASTARGET; }
            set { SetPropertyValue<string>(nameof(ALIASTARGET), ref fALIASTARGET, value); }
        }
        string fONEALIAS;
        [Size(5)]
        public string ONEALIAS
        {
            get { return fONEALIAS; }
            set { SetPropertyValue<string>(nameof(ONEALIAS), ref fONEALIAS, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("RAMKAW")]
            public int RAMKAW { get; set; }
            [Persistent("GLCOUNT")]
            public int GLCOUNT { get; set; }
            [Size(2)]
            [Persistent("SPISONE")]
            public string SPISONE { get; set; }
            [Size(40)]
            [Persistent("ALIASNOM")]
            public string ALIASNOM { get; set; }
            [Size(7)]
            [Persistent("GLASSALIAS")]
            public string GLASSALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
