//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ONE : XPLiteObject
    {
        string fONENAME;
        [Size(30)]
        public string ONENAME
        {
            get { return fONENAME; }
            set { SetPropertyValue<string>(nameof(ONENAME), ref fONENAME, value); }
        }
        string fONEALIAS;
        [Key]
        [Size(5)]
        public string ONEALIAS
        {
            get { return fONEALIAS; }
            set { SetPropertyValue<string>(nameof(ONEALIAS), ref fONEALIAS, value); }
        }
    }

}
