//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class OPZS_REEXPORT : XPLiteObject
    {
        DateTime fREEXPORT_DAY;
        [Key]
        public DateTime REEXPORT_DAY
        {
            get { return fREEXPORT_DAY; }
            set { SetPropertyValue<DateTime>(nameof(REEXPORT_DAY), ref fREEXPORT_DAY, value); }
        }
    }

}
