//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ORDER_ROW : XPLiteObject
    {
        string fFORMULA;
        [Size(150)]
        public string FORMULA
        {
            get { return fFORMULA; }
            set { SetPropertyValue<string>(nameof(FORMULA), ref fFORMULA, value); }
        }
        string fSPCUSTOMERID;
        [Size(30)]
        public string SPCUSTOMERID
        {
            get { return fSPCUSTOMERID; }
            set { SetPropertyValue<string>(nameof(SPCUSTOMERID), ref fSPCUSTOMERID, value); }
        }
        string fORDERCUSTOMERNUM;
        [Size(50)]
        public string ORDERCUSTOMERNUM
        {
            get { return fORDERCUSTOMERNUM; }
            set { SetPropertyValue<string>(nameof(ORDERCUSTOMERNUM), ref fORDERCUSTOMERNUM, value); }
        }
        decimal fWIDTH;
        public decimal WIDTH
        {
            get { return fWIDTH; }
            set { SetPropertyValue<decimal>(nameof(WIDTH), ref fWIDTH, value); }
        }
        decimal fHEIGHT;
        public decimal HEIGHT
        {
            get { return fHEIGHT; }
            set { SetPropertyValue<decimal>(nameof(HEIGHT), ref fHEIGHT, value); }
        }
        int fIZDCOUNT;
        public int IZDCOUNT
        {
            get { return fIZDCOUNT; }
            set { SetPropertyValue<int>(nameof(IZDCOUNT), ref fIZDCOUNT, value); }
        }
        int fIZDREDY;
        [ColumnDbDefaultValue("0")]
        public int IZDREDY
        {
            get { return fIZDREDY; }
            set { SetPropertyValue<int>(nameof(IZDREDY), ref fIZDREDY, value); }
        }
        int fIZDWORK;
        [ColumnDbDefaultValue("0")]
        public int IZDWORK
        {
            get { return fIZDWORK; }
            set { SetPropertyValue<int>(nameof(IZDWORK), ref fIZDWORK, value); }
        }
        int fSPID;
        public int SPID
        {
            get { return fSPID; }
            set { SetPropertyValue<int>(nameof(SPID), ref fSPID, value); }
        }
        string fBARCODE;
        [Size(50)]
        public string BARCODE
        {
            get { return fBARCODE; }
            set { SetPropertyValue<string>(nameof(BARCODE), ref fBARCODE, value); }
        }
        string fCUSTOMERFORMID;
        [Size(20)]
        public string CUSTOMERFORMID
        {
            get { return fCUSTOMERFORMID; }
            set { SetPropertyValue<string>(nameof(CUSTOMERFORMID), ref fCUSTOMERFORMID, value); }
        }
        string fMARK;
        [Size(200)]
        public string MARK
        {
            get { return fMARK; }
            set { SetPropertyValue<string>(nameof(MARK), ref fMARK, value); }
        }
        string fKOMENT;
        [Size(200)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        string fFORMID;
        [Size(3)]
        public string FORMID
        {
            get { return fFORMID; }
            set { SetPropertyValue<string>(nameof(FORMID), ref fFORMID, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("ORDERID")]
            public int ORDERID { get; set; }
            [Persistent("ORDERROWNUM")]
            public int ORDERROWNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
