//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ORDER : XPLiteObject
    {
        DateTime fDATEDOC;
        public DateTime DATEDOC
        {
            get { return fDATEDOC; }
            set { SetPropertyValue<DateTime>(nameof(DATEDOC), ref fDATEDOC, value); }
        }
        DateTime fDATELASTEDIT;
        public DateTime DATELASTEDIT
        {
            get { return fDATELASTEDIT; }
            set { SetPropertyValue<DateTime>(nameof(DATELASTEDIT), ref fDATELASTEDIT, value); }
        }
        DateTime fDATEINPUT;
        public DateTime DATEINPUT
        {
            get { return fDATEINPUT; }
            set { SetPropertyValue<DateTime>(nameof(DATEINPUT), ref fDATEINPUT, value); }
        }
        DateTime fDATECUSTOMER;
        public DateTime DATECUSTOMER
        {
            get { return fDATECUSTOMER; }
            set { SetPropertyValue<DateTime>(nameof(DATECUSTOMER), ref fDATECUSTOMER, value); }
        }
        int fORDERID;
        [Key]
        public int ORDERID
        {
            get { return fORDERID; }
            set { SetPropertyValue<int>(nameof(ORDERID), ref fORDERID, value); }
        }
        int fORDERNUM;
        public int ORDERNUM
        {
            get { return fORDERNUM; }
            set { SetPropertyValue<int>(nameof(ORDERNUM), ref fORDERNUM, value); }
        }
        string fORDERCUSTOMERNUM;
        [Size(50)]
        public string ORDERCUSTOMERNUM
        {
            get { return fORDERCUSTOMERNUM; }
            set { SetPropertyValue<string>(nameof(ORDERCUSTOMERNUM), ref fORDERCUSTOMERNUM, value); }
        }
        int fDOGOVORID;
        public int DOGOVORID
        {
            get { return fDOGOVORID; }
            set { SetPropertyValue<int>(nameof(DOGOVORID), ref fDOGOVORID, value); }
        }
        ORDER_SATUS fSTATENUM;
        [ColumnDbDefaultValue("0")]
        [Association(@"ORDERReferencesORDER_SATUS")]
        public ORDER_SATUS STATENUM
        {
            get { return fSTATENUM; }
            set { SetPropertyValue<ORDER_SATUS>(nameof(STATENUM), ref fSTATENUM, value); }
        }
        CUSTOMER fCUSTOMERALIAS;
        [Size(20)]
        [Association(@"ORDERReferencesCUSTOMER")]
        public CUSTOMER CUSTOMERALIAS
        {
            get { return fCUSTOMERALIAS; }
            set { SetPropertyValue<CUSTOMER>(nameof(CUSTOMERALIAS), ref fCUSTOMERALIAS, value); }
        }
        string fKOMENT;
        [Size(200)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        string fADRESGRUZ;
        public string ADRESGRUZ
        {
            get { return fADRESGRUZ; }
            set { SetPropertyValue<string>(nameof(ADRESGRUZ), ref fADRESGRUZ, value); }
        }
        string fINPUTMANAGER;
        [Size(31)]
        public string INPUTMANAGER
        {
            get { return fINPUTMANAGER; }
            set { SetPropertyValue<string>(nameof(INPUTMANAGER), ref fINPUTMANAGER, value); }
        }
        string fEDITMANAGER;
        [Size(31)]
        public string EDITMANAGER
        {
            get { return fEDITMANAGER; }
            set { SetPropertyValue<string>(nameof(EDITMANAGER), ref fEDITMANAGER, value); }
        }
    }

}
