//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ORDER_SATUS : XPLiteObject
    {
        string fSTATENAME;
        [Size(50)]
        public string STATENAME
        {
            get { return fSTATENAME; }
            set { SetPropertyValue<string>(nameof(STATENAME), ref fSTATENAME, value); }
        }
        int fSTATECOLOR;
        [ColumnDbDefaultValue("0")]
        public int STATECOLOR
        {
            get { return fSTATECOLOR; }
            set { SetPropertyValue<int>(nameof(STATECOLOR), ref fSTATECOLOR, value); }
        }
        short fSTATENUM;
        [Key]
        public short STATENUM
        {
            get { return fSTATENUM; }
            set { SetPropertyValue<short>(nameof(STATENUM), ref fSTATENUM, value); }
        }
        string fSTATESHORTNAME;
        [Size(20)]
        public string STATESHORTNAME
        {
            get { return fSTATESHORTNAME; }
            set { SetPropertyValue<string>(nameof(STATESHORTNAME), ref fSTATESHORTNAME, value); }
        }
        string fSTATEKOMENT;
        [Size(200)]
        public string STATEKOMENT
        {
            get { return fSTATEKOMENT; }
            set { SetPropertyValue<string>(nameof(STATEKOMENT), ref fSTATEKOMENT, value); }
        }
        [Association(@"ORDERReferencesORDER_SATUS")]
        public XPCollection<ORDER> ORDERs { get { return GetCollection<ORDER>(nameof(ORDERs)); } }
    }

}
