//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ORDER_ROWDETAIL : XPLiteObject
    {
        string fCOLUMNVALUE;
        public string COLUMNVALUE
        {
            get { return fCOLUMNVALUE; }
            set { SetPropertyValue<string>(nameof(COLUMNVALUE), ref fCOLUMNVALUE, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("ORDERID")]
            public int ORDERID { get; set; }
            [Persistent("ORDERROWNUM")]
            public int ORDERROWNUM { get; set; }
            [Size(50)]
            [Persistent("COLUMNNAME")]
            public string COLUMNNAME { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
