//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class OTDEL : XPLiteObject
    {
        string fKODOTD;
        [Key]
        [Size(14)]
        public string KODOTD
        {
            get { return fKODOTD; }
            set { SetPropertyValue<string>(nameof(KODOTD), ref fKODOTD, value); }
        }
        string fNAMEOTD;
        [Size(20)]
        public string NAMEOTD
        {
            get { return fNAMEOTD; }
            set { SetPropertyValue<string>(nameof(NAMEOTD), ref fNAMEOTD, value); }
        }
        short fPEAPCOUNT;
        public short PEAPCOUNT
        {
            get { return fPEAPCOUNT; }
            set { SetPropertyValue<short>(nameof(PEAPCOUNT), ref fPEAPCOUNT, value); }
        }
        string fRUKKODL;
        [Size(25)]
        public string RUKKODL
        {
            get { return fRUKKODL; }
            set { SetPropertyValue<string>(nameof(RUKKODL), ref fRUKKODL, value); }
        }
        string fPOISK;
        [Size(1)]
        public string POISK
        {
            get { return fPOISK; }
            set { SetPropertyValue<string>(nameof(POISK), ref fPOISK, value); }
        }
        string fARHIV;
        [Size(1)]
        public string ARHIV
        {
            get { return fARHIV; }
            set { SetPropertyValue<string>(nameof(ARHIV), ref fARHIV, value); }
        }
    }

}
