//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class OUTCROPSIZE : XPLiteObject
    {
        int fSIZEOUTCROP;
        public int SIZEOUTCROP
        {
            get { return fSIZEOUTCROP; }
            set { SetPropertyValue<int>(nameof(SIZEOUTCROP), ref fSIZEOUTCROP, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("TYPEOUTCROP")]
            public short TYPEOUTCROP { get; set; }
            [Persistent("GLASSSIZE")]
            public short GLASSSIZE { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
