//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class OUTCROPTYPE : XPLiteObject
    {
        int fOUTCROPID;
        [Key]
        public int OUTCROPID
        {
            get { return fOUTCROPID; }
            set { SetPropertyValue<int>(nameof(OUTCROPID), ref fOUTCROPID, value); }
        }
        string fOUTCROPNAME;
        public string OUTCROPNAME
        {
            get { return fOUTCROPNAME; }
            set { SetPropertyValue<string>(nameof(OUTCROPNAME), ref fOUTCROPNAME, value); }
        }
    }

}
