//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PACKETS : XPLiteObject
    {
        DateTime fDATEREAL;
        [ColumnDbDefaultValue("null")]
        public DateTime DATEREAL
        {
            get { return fDATEREAL; }
            set { SetPropertyValue<DateTime>(nameof(DATEREAL), ref fDATEREAL, value); }
        }
        DateTime fDATEAVTO;
        [ColumnDbDefaultValue("null")]
        public DateTime DATEAVTO
        {
            get { return fDATEAVTO; }
            set { SetPropertyValue<DateTime>(nameof(DATEAVTO), ref fDATEAVTO, value); }
        }
        DateTime fDATEOTGRUZ;
        [ColumnDbDefaultValue("null")]
        public DateTime DATEOTGRUZ
        {
            get { return fDATEOTGRUZ; }
            set { SetPropertyValue<DateTime>(nameof(DATEOTGRUZ), ref fDATEOTGRUZ, value); }
        }
        string fREGDOCID;
        [Size(14)]
        [ColumnDbDefaultValue("null")]
        public string REGDOCID
        {
            get { return fREGDOCID; }
            set { SetPropertyValue<string>(nameof(REGDOCID), ref fREGDOCID, value); }
        }
        DateTime fDATEDOST;
        [ColumnDbDefaultValue("null")]
        public DateTime DATEDOST
        {
            get { return fDATEDOST; }
            set { SetPropertyValue<DateTime>(nameof(DATEDOST), ref fDATEDOST, value); }
        }
        int fSTATENUM;
        [ColumnDbDefaultValue("2")]
        public int STATENUM
        {
            get { return fSTATENUM; }
            set { SetPropertyValue<int>(nameof(STATENUM), ref fSTATENUM, value); }
        }
        int fTEAMID0;
        [ColumnDbDefaultValue("null")]
        public int TEAMID0
        {
            get { return fTEAMID0; }
            set { SetPropertyValue<int>(nameof(TEAMID0), ref fTEAMID0, value); }
        }
        int fTEAMID1;
        [ColumnDbDefaultValue("null")]
        public int TEAMID1
        {
            get { return fTEAMID1; }
            set { SetPropertyValue<int>(nameof(TEAMID1), ref fTEAMID1, value); }
        }
        int fLINENUM;
        [ColumnDbDefaultValue("null")]
        public int LINENUM
        {
            get { return fLINENUM; }
            set { SetPropertyValue<int>(nameof(LINENUM), ref fLINENUM, value); }
        }
        int fLOADID;
        [ColumnDbDefaultValue("null")]
        public int LOADID
        {
            get { return fLOADID; }
            set { SetPropertyValue<int>(nameof(LOADID), ref fLOADID, value); }
        }
        int fTEAMID3;
        [ColumnDbDefaultValue("null")]
        public int TEAMID3
        {
            get { return fTEAMID3; }
            set { SetPropertyValue<int>(nameof(TEAMID3), ref fTEAMID3, value); }
        }
        string fAVTO;
        [Size(40)]
        [ColumnDbDefaultValue("null")]
        public string AVTO
        {
            get { return fAVTO; }
            set { SetPropertyValue<string>(nameof(AVTO), ref fAVTO, value); }
        }
        string fSENDTOPARENT;
        [Size(1)]
        [ColumnDbDefaultValue("null")]
        public string SENDTOPARENT
        {
            get { return fSENDTOPARENT; }
            set { SetPropertyValue<string>(nameof(SENDTOPARENT), ref fSENDTOPARENT, value); }
        }
        string fKILLERNAME;
        [Size(31)]
        [ColumnDbDefaultValue("null")]
        public string KILLERNAME
        {
            get { return fKILLERNAME; }
            set { SetPropertyValue<string>(nameof(KILLERNAME), ref fKILLERNAME, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(14)]
            [Persistent("CUSTID")]
            public string CUSTID { get; set; }
            [Persistent("ROWNUM")]
            public int ROWNUM { get; set; }
            [Persistent("IZDNUM")]
            public int IZDNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
