//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_FIELDS_HEAD : XPLiteObject
    {
        int fHF_ID;
        [Key]
        public int HF_ID
        {
            get { return fHF_ID; }
            set { SetPropertyValue<int>(nameof(HF_ID), ref fHF_ID, value); }
        }
        string fHF_NAME;
        [Indexed(Name = @"UNQ1_PARSER_FIELDS_HEAD", Unique = true)]
        [Size(50)]
        public string HF_NAME
        {
            get { return fHF_NAME; }
            set { SetPropertyValue<string>(nameof(HF_NAME), ref fHF_NAME, value); }
        }
        string fHF_DESCRIPTION;
        [Size(50)]
        public string HF_DESCRIPTION
        {
            get { return fHF_DESCRIPTION; }
            set { SetPropertyValue<string>(nameof(HF_DESCRIPTION), ref fHF_DESCRIPTION, value); }
        }
    }

}
