//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_TABLE : XPLiteObject
    {
        int fTF_CALCTYPE;
        [ColumnDbDefaultValue("0")]
        public int TF_CALCTYPE
        {
            get { return fTF_CALCTYPE; }
            set { SetPropertyValue<int>(nameof(TF_CALCTYPE), ref fTF_CALCTYPE, value); }
        }
        string fTF_FORMULA;
        public string TF_FORMULA
        {
            get { return fTF_FORMULA; }
            set { SetPropertyValue<string>(nameof(TF_FORMULA), ref fTF_FORMULA, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PARSERID")]
            public int PARSERID { get; set; }
            [Persistent("TF_ID")]
            public int TF_ID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
