//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_CALCTYPE : XPLiteObject
    {
        string fCALCTYPENAME;
        [Indexed(Name = @"UNQ1_PARSER_CALCTYPE", Unique = true)]
        [Size(30)]
        public string CALCTYPENAME
        {
            get { return fCALCTYPENAME; }
            set { SetPropertyValue<string>(nameof(CALCTYPENAME), ref fCALCTYPENAME, value); }
        }
        int fPARSER_CALCTYPEID;
        [Key]
        public int PARSER_CALCTYPEID
        {
            get { return fPARSER_CALCTYPEID; }
            set { SetPropertyValue<int>(nameof(PARSER_CALCTYPEID), ref fPARSER_CALCTYPEID, value); }
        }
    }

}
