//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_FIELDS_TABLE : XPLiteObject
    {
        int fTF_ID;
        [Key]
        public int TF_ID
        {
            get { return fTF_ID; }
            set { SetPropertyValue<int>(nameof(TF_ID), ref fTF_ID, value); }
        }
        string fTF_NAME;
        [Indexed(Name = @"UNQ1_PARSER_FIELDS_TABLE", Unique = true)]
        [Size(50)]
        public string TF_NAME
        {
            get { return fTF_NAME; }
            set { SetPropertyValue<string>(nameof(TF_NAME), ref fTF_NAME, value); }
        }
        string fTF_DESCRIPTION;
        [Size(50)]
        public string TF_DESCRIPTION
        {
            get { return fTF_DESCRIPTION; }
            set { SetPropertyValue<string>(nameof(TF_DESCRIPTION), ref fTF_DESCRIPTION, value); }
        }
    }

}
