//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_TABLE_ADR : XPLiteObject
    {
        int fTF_COLUMN;
        public int TF_COLUMN
        {
            get { return fTF_COLUMN; }
            set { SetPropertyValue<int>(nameof(TF_COLUMN), ref fTF_COLUMN, value); }
        }
        int fTF_ROW;
        public int TF_ROW
        {
            get { return fTF_ROW; }
            set { SetPropertyValue<int>(nameof(TF_ROW), ref fTF_ROW, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PARSERID")]
            public int PARSERID { get; set; }
            [Persistent("TF_ID")]
            public int TF_ID { get; set; }
            [Persistent("NUM")]
            public int NUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
