//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER : XPLiteObject
    {
        string fPROG_NAME;
        [Size(70)]
        public string PROG_NAME
        {
            get { return fPROG_NAME; }
            set { SetPropertyValue<string>(nameof(PROG_NAME), ref fPROG_NAME, value); }
        }
        int fPARSERID;
        [Key]
        public int PARSERID
        {
            get { return fPARSERID; }
            set { SetPropertyValue<int>(nameof(PARSERID), ref fPARSERID, value); }
        }
        string fPARSER_NAME;
        [Indexed(Name = @"UNQ1_PARSER", Unique = true)]
        [Size(50)]
        public string PARSER_NAME
        {
            get { return fPARSER_NAME; }
            set { SetPropertyValue<string>(nameof(PARSER_NAME), ref fPARSER_NAME, value); }
        }
    }

}
