//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_HEAD_ADR : XPLiteObject
    {
        int fHF_COLUMN;
        public int HF_COLUMN
        {
            get { return fHF_COLUMN; }
            set { SetPropertyValue<int>(nameof(HF_COLUMN), ref fHF_COLUMN, value); }
        }
        int fHF_ROW;
        public int HF_ROW
        {
            get { return fHF_ROW; }
            set { SetPropertyValue<int>(nameof(HF_ROW), ref fHF_ROW, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PARSERID")]
            public int PARSERID { get; set; }
            [Persistent("HF_ID")]
            public int HF_ID { get; set; }
            [Persistent("NUM")]
            public int NUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
