//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PARSER_HEAD : XPLiteObject
    {
        int fHF_CALCTYPE;
        [ColumnDbDefaultValue("0")]
        public int HF_CALCTYPE
        {
            get { return fHF_CALCTYPE; }
            set { SetPropertyValue<int>(nameof(HF_CALCTYPE), ref fHF_CALCTYPE, value); }
        }
        string fHF_FORMULA;
        public string HF_FORMULA
        {
            get { return fHF_FORMULA; }
            set { SetPropertyValue<string>(nameof(HF_FORMULA), ref fHF_FORMULA, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PARSERID")]
            public int PARSERID { get; set; }
            [Persistent("HF_ID")]
            public int HF_ID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
