//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PASP : XPLiteObject
    {
        string fPARNAME;
        [Size(30)]
        public string PARNAME
        {
            get { return fPARNAME; }
            set { SetPropertyValue<string>(nameof(PARNAME), ref fPARNAME, value); }
        }
        string fPARALIAS;
        [Key]
        [Size(10)]
        public string PARALIAS
        {
            get { return fPARALIAS; }
            set { SetPropertyValue<string>(nameof(PARALIAS), ref fPARALIAS, value); }
        }
        string fPARVALUE;
        [Size(50)]
        public string PARVALUE
        {
            get { return fPARVALUE; }
            set { SetPropertyValue<string>(nameof(PARVALUE), ref fPARVALUE, value); }
        }
    }

}
