//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PLATFORM : XPLiteObject
    {
        string fPLATFORMC1C;
        [Size(6)]
        public string PLATFORMC1C
        {
            get { return fPLATFORMC1C; }
            set { SetPropertyValue<string>(nameof(PLATFORMC1C), ref fPLATFORMC1C, value); }
        }
        string fFULLNMAE;
        [Size(50)]
        public string FULLNMAE
        {
            get { return fFULLNMAE; }
            set { SetPropertyValue<string>(nameof(FULLNMAE), ref fFULLNMAE, value); }
        }
        int fPLATFORMNUM;
        public int PLATFORMNUM
        {
            get { return fPLATFORMNUM; }
            set { SetPropertyValue<int>(nameof(PLATFORMNUM), ref fPLATFORMNUM, value); }
        }
        short fPLATFORMID;
        [Key]
        [ColumnDbDefaultValue("0")]
        public short PLATFORMID
        {
            get { return fPLATFORMID; }
            set { SetPropertyValue<short>(nameof(PLATFORMID), ref fPLATFORMID, value); }
        }
        string fVIEWNAME;
        [Size(15)]
        public string VIEWNAME
        {
            get { return fVIEWNAME; }
            set { SetPropertyValue<string>(nameof(VIEWNAME), ref fVIEWNAME, value); }
        }
        string fSHORTNAME;
        [Size(15)]
        public string SHORTNAME
        {
            get { return fSHORTNAME; }
            set { SetPropertyValue<string>(nameof(SHORTNAME), ref fSHORTNAME, value); }
        }
        [Association(@"CUSTReferencesPLATFORM")]
        public XPCollection<CUST> CUSTs { get { return GetCollection<CUST>(nameof(CUSTs)); } }
    }

}
