//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class POOLS : XPLiteObject
    {
        string fPOOLNAME;
        [Size(30)]
        public string POOLNAME
        {
            get { return fPOOLNAME; }
            set { SetPropertyValue<string>(nameof(POOLNAME), ref fPOOLNAME, value); }
        }
        DateTime fPOOLDATE;
        public DateTime POOLDATE
        {
            get { return fPOOLDATE; }
            set { SetPropertyValue<DateTime>(nameof(POOLDATE), ref fPOOLDATE, value); }
        }
        string fPOOLTIME;
        [Size(10)]
        public string POOLTIME
        {
            get { return fPOOLTIME; }
            set { SetPropertyValue<string>(nameof(POOLTIME), ref fPOOLTIME, value); }
        }
        int fPOOLNUMBER;
        public int POOLNUMBER
        {
            get { return fPOOLNUMBER; }
            set { SetPropertyValue<int>(nameof(POOLNUMBER), ref fPOOLNUMBER, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("POOLID")]
            public int POOLID { get; set; }
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
