//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PP_GRANT : XPLiteObject
    {
        int fGRANT_ID;
        [Key]
        public int GRANT_ID
        {
            get { return fGRANT_ID; }
            set { SetPropertyValue<int>(nameof(GRANT_ID), ref fGRANT_ID, value); }
        }
        string fGRANT_NAME;
        [Indexed(Name = @"UNQ1_PP_GRANT", Unique = true)]
        public string GRANT_NAME
        {
            get { return fGRANT_NAME; }
            set { SetPropertyValue<string>(nameof(GRANT_NAME), ref fGRANT_NAME, value); }
        }
    }

}
