//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PP_ROLE : XPLiteObject
    {
        int fROLE_ID;
        [Key]
        public int ROLE_ID
        {
            get { return fROLE_ID; }
            set { SetPropertyValue<int>(nameof(ROLE_ID), ref fROLE_ID, value); }
        }
        string fROLE_NAME;
        [Indexed(Name = @"UNQ1_PP_ROLE", Unique = true)]
        [Size(50)]
        public string ROLE_NAME
        {
            get { return fROLE_NAME; }
            set { SetPropertyValue<string>(nameof(ROLE_NAME), ref fROLE_NAME, value); }
        }
        string fROLE_OLD_PREF;
        [Size(10)]
        public string ROLE_OLD_PREF
        {
            get { return fROLE_OLD_PREF; }
            set { SetPropertyValue<string>(nameof(ROLE_OLD_PREF), ref fROLE_OLD_PREF, value); }
        }
        string fROLE_ALLPLATFORM;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string ROLE_ALLPLATFORM
        {
            get { return fROLE_ALLPLATFORM; }
            set { SetPropertyValue<string>(nameof(ROLE_ALLPLATFORM), ref fROLE_ALLPLATFORM, value); }
        }
    }

}
