//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PP_USER_ROLE : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("ROLE_ID")]
            public int ROLE_ID { get; set; }
            [Persistent("PLATFORM")]
            public int PLATFORM { get; set; }
            [Size(31)]
            [Persistent("USER_LOGIN")]
            public string USER_LOGIN { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
