//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PPCUST : XPLiteObject
    {
        double fPRICE;
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        DateTime fDT_EDIT;
        [ColumnDbDefaultValue("current_timestamp\r\n")]
        public DateTime DT_EDIT
        {
            get { return fDT_EDIT; }
            set { SetPropertyValue<DateTime>(nameof(DT_EDIT), ref fDT_EDIT, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("S")]
            public double S { get; set; }
            [Size(20)]
            [Persistent("ALIAS")]
            public string ALIAS { get; set; }
            [Persistent("K")]
            public short K { get; set; }
            [Size(5)]
            [Persistent("SIZ")]
            public string SIZ { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
