//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICE_BASE : XPLiteObject
    {
        double fPRICE;
        [ColumnDbDefaultValue("0")]
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        double fRECALC_RATIO;
        [ColumnDbDefaultValue("1")]
        public double RECALC_RATIO
        {
            get { return fRECALC_RATIO; }
            set { SetPropertyValue<double>(nameof(RECALC_RATIO), ref fRECALC_RATIO, value); }
        }
        double fRECALC_BASEDELTA;
        [ColumnDbDefaultValue("0")]
        public double RECALC_BASEDELTA
        {
            get { return fRECALC_BASEDELTA; }
            set { SetPropertyValue<double>(nameof(RECALC_BASEDELTA), ref fRECALC_BASEDELTA, value); }
        }
        double fRECALC_DELTA;
        [ColumnDbDefaultValue("0")]
        public double RECALC_DELTA
        {
            get { return fRECALC_DELTA; }
            set { SetPropertyValue<double>(nameof(RECALC_DELTA), ref fRECALC_DELTA, value); }
        }
        DateTime fEDIT;
        public DateTime EDIT
        {
            get { return fEDIT; }
            set { SetPropertyValue<DateTime>(nameof(EDIT), ref fEDIT, value); }
        }
        int fBPBID;
        public int BPBID
        {
            get { return fBPBID; }
            set { SetPropertyValue<int>(nameof(BPBID), ref fBPBID, value); }
        }
        short fRECALC_TYPE;
        [ColumnDbDefaultValue("0")]
        public short RECALC_TYPE
        {
            get { return fRECALC_TYPE; }
            set { SetPropertyValue<short>(nameof(RECALC_TYPE), ref fRECALC_TYPE, value); }
        }
        string fEDITOR;
        [Size(31)]
        public string EDITOR
        {
            get { return fEDITOR; }
            set { SetPropertyValue<string>(nameof(EDITOR), ref fEDITOR, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("SQUID")]
            public int SQUID { get; set; }
            [Persistent("PBID")]
            public int PBID { get; set; }
            [Persistent("PRICEID")]
            public int PRICEID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
