//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICES : XPLiteObject
    {
        DateTime fDATEBEGIN;
        public DateTime DATEBEGIN
        {
            get { return fDATEBEGIN; }
            set { SetPropertyValue<DateTime>(nameof(DATEBEGIN), ref fDATEBEGIN, value); }
        }
        DateTime fDATEEND;
        public DateTime DATEEND
        {
            get { return fDATEEND; }
            set { SetPropertyValue<DateTime>(nameof(DATEEND), ref fDATEEND, value); }
        }
        int fPRICEID;
        [Key]
        public int PRICEID
        {
            get { return fPRICEID; }
            set { SetPropertyValue<int>(nameof(PRICEID), ref fPRICEID, value); }
        }
        string fPRNAME;
        [Size(50)]
        public string PRNAME
        {
            get { return fPRNAME; }
            set { SetPropertyValue<string>(nameof(PRNAME), ref fPRNAME, value); }
        }
        PRICESTYPE fPRTYPE;
        [Association(@"PRICESReferencesPRICESTYPE")]
        public PRICESTYPE PRTYPE
        {
            get { return fPRTYPE; }
            set { SetPropertyValue<PRICESTYPE>(nameof(PRTYPE), ref fPRTYPE, value); }
        }
        string fPRCODENAME;
        [Indexed(@"PRTYPE", Name = @"UNQ1_PRICES", Unique = true)]
        [Size(3)]
        public string PRCODENAME
        {
            get { return fPRCODENAME; }
            set { SetPropertyValue<string>(nameof(PRCODENAME), ref fPRCODENAME, value); }
        }
    }

}
