//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICESTYPE : XPLiteObject
    {
        string fPRICETYPENAME;
        [Size(30)]
        public string PRICETYPENAME
        {
            get { return fPRICETYPENAME; }
            set { SetPropertyValue<string>(nameof(PRICETYPENAME), ref fPRICETYPENAME, value); }
        }
        int fPRICETYPEID;
        [Key]
        public int PRICETYPEID
        {
            get { return fPRICETYPEID; }
            set { SetPropertyValue<int>(nameof(PRICETYPEID), ref fPRICETYPEID, value); }
        }
        [Association(@"PRICESReferencesPRICESTYPE")]
        public XPCollection<PRICES> PRICESCollection { get { return GetCollection<PRICES>(nameof(PRICESCollection)); } }
    }

}
