//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICESPROS : XPLiteObject
    {
        double fPRICEMP;
        [ColumnDbDefaultValue("0")]
        public double PRICEMP
        {
            get { return fPRICEMP; }
            set { SetPropertyValue<double>(nameof(PRICEMP), ref fPRICEMP, value); }
        }
        double fPRICET;
        [ColumnDbDefaultValue("0")]
        public double PRICET
        {
            get { return fPRICET; }
            set { SetPropertyValue<double>(nameof(PRICET), ref fPRICET, value); }
        }
        double fPRICEX;
        [ColumnDbDefaultValue("0")]
        public double PRICEX
        {
            get { return fPRICEX; }
            set { SetPropertyValue<double>(nameof(PRICEX), ref fPRICEX, value); }
        }
        double fPRICEY;
        [ColumnDbDefaultValue("0")]
        public double PRICEY
        {
            get { return fPRICEY; }
            set { SetPropertyValue<double>(nameof(PRICEY), ref fPRICEY, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
            [Size(20)]
            [Persistent("SPROSALIAS")]
            public string SPROSALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
