//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICE_BFORMULA : XPLiteObject
    {
        int fPBID;
        [Key]
        public int PBID
        {
            get { return fPBID; }
            set { SetPropertyValue<int>(nameof(PBID), ref fPBID, value); }
        }
        int fTHICKNESSGLASS1;
        public int THICKNESSGLASS1
        {
            get { return fTHICKNESSGLASS1; }
            set { SetPropertyValue<int>(nameof(THICKNESSGLASS1), ref fTHICKNESSGLASS1, value); }
        }
        int fTHICKNESSGLASS2;
        public int THICKNESSGLASS2
        {
            get { return fTHICKNESSGLASS2; }
            set { SetPropertyValue<int>(nameof(THICKNESSGLASS2), ref fTHICKNESSGLASS2, value); }
        }
        int fTHICKNESSGLASS3;
        public int THICKNESSGLASS3
        {
            get { return fTHICKNESSGLASS3; }
            set { SetPropertyValue<int>(nameof(THICKNESSGLASS3), ref fTHICKNESSGLASS3, value); }
        }
    }

}
