//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICE_FILM : XPLiteObject
    {
        double fFILMPRICE;
        [ColumnDbDefaultValue("0")]
        public double FILMPRICE
        {
            get { return fFILMPRICE; }
            set { SetPropertyValue<double>(nameof(FILMPRICE), ref fFILMPRICE, value); }
        }
        DateTime fEDIT;
        public DateTime EDIT
        {
            get { return fEDIT; }
            set { SetPropertyValue<DateTime>(nameof(EDIT), ref fEDIT, value); }
        }
        string fEDITOR;
        [Size(31)]
        public string EDITOR
        {
            get { return fEDITOR; }
            set { SetPropertyValue<string>(nameof(EDITOR), ref fEDITOR, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("PRICEID")]
            public int PRICEID { get; set; }
            [Size(20)]
            [Persistent("FILMNAME")]
            public string FILMNAME { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
