//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICEGLASS : XPLiteObject
    {
        double fPRICEV3;
        public double PRICEV3
        {
            get { return fPRICEV3; }
            set { SetPropertyValue<double>(nameof(PRICEV3), ref fPRICEV3, value); }
        }
        double fPRICEONE;
        public double PRICEONE
        {
            get { return fPRICEONE; }
            set { SetPropertyValue<double>(nameof(PRICEONE), ref fPRICEONE, value); }
        }
        double fPRICESKLAD;
        public double PRICESKLAD
        {
            get { return fPRICESKLAD; }
            set { SetPropertyValue<double>(nameof(PRICESKLAD), ref fPRICESKLAD, value); }
        }
        DateTime fDT_EDIT;
        [ColumnDbDefaultValue("current_timestamp\r\n")]
        public DateTime DT_EDIT
        {
            get { return fDT_EDIT; }
            set { SetPropertyValue<DateTime>(nameof(DT_EDIT), ref fDT_EDIT, value); }
        }
        string fMARKA;
        [Size(20)]
        public string MARKA
        {
            get { return fMARKA; }
            set { SetPropertyValue<string>(nameof(MARKA), ref fMARKA, value); }
        }
        string fALIASPODR;
        [Size(20)]
        public string ALIASPODR
        {
            get { return fALIASPODR; }
            set { SetPropertyValue<string>(nameof(ALIASPODR), ref fALIASPODR, value); }
        }
        string fGLASSID_1C;
        [Size(20)]
        public string GLASSID_1C
        {
            get { return fGLASSID_1C; }
            set { SetPropertyValue<string>(nameof(GLASSID_1C), ref fGLASSID_1C, value); }
        }
        string fSIZ_;
        [Size(5)]
        public string SIZ_
        {
            get { return fSIZ_; }
            set { SetPropertyValue<string>(nameof(SIZ_), ref fSIZ_, value); }
        }
        string fZAKAZ;
        [Size(3)]
        public string ZAKAZ
        {
            get { return fZAKAZ; }
            set { SetPropertyValue<string>(nameof(ZAKAZ), ref fZAKAZ, value); }
        }
        string fIS_TRP;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string IS_TRP
        {
            get { return fIS_TRP; }
            set { SetPropertyValue<string>(nameof(IS_TRP), ref fIS_TRP, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
            [Size(7)]
            [Persistent("GLASSALIAS")]
            public string GLASSALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
