//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICEFILM : XPLiteObject
    {
        double fPRICE;
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        DateTime fDT_EDIT;
        [ColumnDbDefaultValue("current_timestamp\r\n")]
        public DateTime DT_EDIT
        {
            get { return fDT_EDIT; }
            set { SetPropertyValue<DateTime>(nameof(DT_EDIT), ref fDT_EDIT, value); }
        }
        string fKOMENT;
        [Size(20)]
        public string KOMENT
        {
            get { return fKOMENT; }
            set { SetPropertyValue<string>(nameof(KOMENT), ref fKOMENT, value); }
        }
        string fALIASPODR;
        [Size(20)]
        public string ALIASPODR
        {
            get { return fALIASPODR; }
            set { SetPropertyValue<string>(nameof(ALIASPODR), ref fALIASPODR, value); }
        }
        string fFILMID_1C;
        [Size(20)]
        [ColumnDbDefaultValue("3800")]
        public string FILMID_1C
        {
            get { return fFILMID_1C; }
            set { SetPropertyValue<string>(nameof(FILMID_1C), ref fFILMID_1C, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("CUSTOMERALIAS")]
            public string CUSTOMERALIAS { get; set; }
            [Size(20)]
            [Persistent("FILMALIAS")]
            public string FILMALIAS { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
