//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICEZAL : XPLiteObject
    {
        double fSIZ_;
        [Key]
        public double SIZ_
        {
            get { return fSIZ_; }
            set { SetPropertyValue<double>(nameof(SIZ_), ref fSIZ_, value); }
        }
        double fPRICE;
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        double fPRICEMAGNIT;
        public double PRICEMAGNIT
        {
            get { return fPRICEMAGNIT; }
            set { SetPropertyValue<double>(nameof(PRICEMAGNIT), ref fPRICEMAGNIT, value); }
        }
        DateTime fDT_EDIT;
        [ColumnDbDefaultValue("current_timestamp\r\n")]
        public DateTime DT_EDIT
        {
            get { return fDT_EDIT; }
            set { SetPropertyValue<DateTime>(nameof(DT_EDIT), ref fDT_EDIT, value); }
        }
    }

}
