//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class PRICE_SLOZ : XPLiteObject
    {
        double fPRICESLOZ;
        [ColumnDbDefaultValue("0")]
        public double PRICESLOZ
        {
            get { return fPRICESLOZ; }
            set { SetPropertyValue<double>(nameof(PRICESLOZ), ref fPRICESLOZ, value); }
        }
        double fDELTA;
        [ColumnDbDefaultValue("0")]
        public double DELTA
        {
            get { return fDELTA; }
            set { SetPropertyValue<double>(nameof(DELTA), ref fDELTA, value); }
        }
        DateTime fEDIT;
        public DateTime EDIT
        {
            get { return fEDIT; }
            set { SetPropertyValue<DateTime>(nameof(EDIT), ref fEDIT, value); }
        }
        decimal fDISCOUNT;
        [ColumnDbDefaultValue("100")]
        public decimal DISCOUNT
        {
            get { return fDISCOUNT; }
            set { SetPropertyValue<decimal>(nameof(DISCOUNT), ref fDISCOUNT, value); }
        }
        string fEDITOR;
        [Size(31)]
        public string EDITOR
        {
            get { return fEDITOR; }
            set { SetPropertyValue<string>(nameof(EDITOR), ref fEDITOR, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("SLOZTYPE")]
            public int SLOZTYPE { get; set; }
            [Persistent("PRICEID")]
            public int PRICEID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
