//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ROWCUST_RESTORATION : XPLiteObject
    {
        string fBRAK_CID;
        [Size(14)]
        public string BRAK_CID
        {
            get { return fBRAK_CID; }
            set { SetPropertyValue<string>(nameof(BRAK_CID), ref fBRAK_CID, value); }
        }
        int fBRAK_ID;
        public int BRAK_ID
        {
            get { return fBRAK_ID; }
            set { SetPropertyValue<int>(nameof(BRAK_ID), ref fBRAK_ID, value); }
        }
        int fBRAK_ROWNUM;
        public int BRAK_ROWNUM
        {
            get { return fBRAK_ROWNUM; }
            set { SetPropertyValue<int>(nameof(BRAK_ROWNUM), ref fBRAK_ROWNUM, value); }
        }
        int fBRAK_GLASSPOS;
        public int BRAK_GLASSPOS
        {
            get { return fBRAK_GLASSPOS; }
            set { SetPropertyValue<int>(nameof(BRAK_GLASSPOS), ref fBRAK_GLASSPOS, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(14)]
            [Persistent("CUSTID")]
            public string CUSTID { get; set; }
            [Persistent("ROWNUM")]
            public int ROWNUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
