//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Socrat.OldDataConnector.Min.RESMIN
{

    public partial class ROWTENDER : XPLiteObject
    {
        double fAREA;
        public double AREA
        {
            get { return fAREA; }
            set { SetPropertyValue<double>(nameof(AREA), ref fAREA, value); }
        }
        double fPRICE;
        public double PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<double>(nameof(PRICE), ref fPRICE, value); }
        }
        double fUSEAREA;
        [ColumnDbDefaultValue("0")]
        public double USEAREA
        {
            get { return fUSEAREA; }
            set { SetPropertyValue<double>(nameof(USEAREA), ref fUSEAREA, value); }
        }
        double fBRAKAREA;
        [ColumnDbDefaultValue("0")]
        public double BRAKAREA
        {
            get { return fBRAKAREA; }
            set { SetPropertyValue<double>(nameof(BRAKAREA), ref fBRAKAREA, value); }
        }
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fTENDER_ID;
        [Indexed(@"TENDERFORMULA_ID", Name = @"ROWTENDER_IDX1", Unique = true)]
        public int TENDER_ID
        {
            get { return fTENDER_ID; }
            set { SetPropertyValue<int>(nameof(TENDER_ID), ref fTENDER_ID, value); }
        }
        int fTENDERFORMULA_ID;
        public int TENDERFORMULA_ID
        {
            get { return fTENDERFORMULA_ID; }
            set { SetPropertyValue<int>(nameof(TENDERFORMULA_ID), ref fTENDERFORMULA_ID, value); }
        }
        short fDEL;
        [ColumnDbDefaultValue("0")]
        public short DEL
        {
            get { return fDEL; }
            set { SetPropertyValue<short>(nameof(DEL), ref fDEL, value); }
        }
        string fUSERNAME;
        [Size(31)]
        public string USERNAME
        {
            get { return fUSERNAME; }
            set { SetPropertyValue<string>(nameof(USERNAME), ref fUSERNAME, value); }
        }
    }

}
