CREATE TABLE [dbo].[CatalogShapeParam] (
    [Id]                        UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [IsCanCutGlass]             BIT              NULL,
    [IsCanBendDistanceFrame]    BIT              NULL,
    [IsCanFormSeal]             BIT              NULL,
    [IsCanGasFillForm]          BIT              NULL,
    [IsCanVertBendMashineRobot] BIT              NULL,
    [IsCanVertMashineEdgeMake]  BIT              NULL,
    [IsToothVector]             BIT              NULL,
    [L_param]                   FLOAT (53)       NULL,
    [H_param]                   FLOAT (53)       NULL,
    [L1_param]                  FLOAT (53)       NULL,
    [L2_param]                  FLOAT (53)       NULL,
    [H1_param]                  FLOAT (53)       NULL,
    [H2_param]                  FLOAT (53)       NULL,
    [R_param]                   FLOAT (53)       NULL,
    [R1_param]                  FLOAT (53)       NULL,
    [R2_param]                  FLOAT (53)       NULL,
    [R3_param]                  FLOAT (53)       NULL,
    [R4_param]                  FLOAT (53)       NULL,
    [Chord_param]               FLOAT (53)       NULL,
    [B1_param]                  FLOAT (53)       NULL,
    [B2_param]                  FLOAT (53)       NULL,
    [B3_param]                  FLOAT (53)       NULL,
    [B4_param]                  FLOAT (53)       NULL,
    [CheckCut1_param]           FLOAT (53)       NULL,
    [CheckCut2_param]           FLOAT (53)       NULL,
    [CheckCut3_param]           FLOAT (53)       NULL,
    [CheckCut4_param]           FLOAT (53)       NULL,
    [CheckCut5_param]           FLOAT (53)       NULL,
    [CheckCut6_param]           FLOAT (53)       NULL,
    [CheckCut7_param]           FLOAT (53)       NULL,
    [CheckCut8_param]           FLOAT (53)       NULL,
    [BaseArea]                  FLOAT (53)       NULL,
    [Area]                      FLOAT (53)       NULL,
    [Perimeter]                 FLOAT (53)       NULL,
    [ShapeKisPersent]           NVARCHAR (10)    NULL,
    [ShapeKis]                  FLOAT (53)       NULL,
    [ShapeHeight]               FLOAT (53)       NULL,
    [ShapeWidth]                FLOAT (53)       NULL,
    [RowVersion]                ROWVERSION       NOT NULL,
    [LastChangedUser]           UNIQUEIDENTIFIER NULL,
    [LastChangedDate]           DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CatalogShapeParam_CatalogShapeShape] FOREIGN KEY ([Id]) REFERENCES [dbo].[CatalogShape] ([Id]) ON DELETE CASCADE
);



